<?php

declare(strict_types=1);

namespace App\Modules\Catalog\Application\Services;

use App\Modules\Catalog\Application\Jobs\GenerateRenditions;
use App\Modules\Catalog\Domain\Enums\MediaAssetType;
use App\Modules\Catalog\Domain\Enums\MediaSource;
use App\Modules\Catalog\Domain\Enums\MediaStatus;
use App\Modules\Catalog\Domain\Media\MediaAsset;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;

/**
 * Service for uploading and registering media assets in the catalog sub-system.
 *
 * Two entry points are provided:
 *
 *  - {@see uploadForProduct}: handles a direct file upload (image-only, stored on S3).
 *  - {@see registerExternalUrl}: registers a third-party image URL (SSRF-safe, display-only).
 *
 * The upload flow mirrors ProductImageService::upload() (Product module):
 *  1. Validate MIME type (two-layer: allow-list constant + Laravel 'image'/'mimes' rules).
 *  2. Compute SHA-256 checksum.
 *  3. Build deterministic storage path: products/{tenant}/{product}/{assetUuid}/original.{ext}
 *  4. PUT the file on S3 BEFORE the DB transaction (avoids a committed row pointing to a missing file).
 *  5. Open a DB::transaction and create the MediaAsset row (status = UPLOADED).
 *  6. After commit, dispatch GenerateRenditions (the job transitions UPLOADED → PROCESSING → READY).
 *  7. On any Throwable, delete the orphaned S3 object and rethrow.
 */
final class MediaUploadService
{
    /**
     * Allowed MIME types for uploaded images.
     * Must stay in sync with UploadMediaRequest::rules() 'mimes:' list.
     *
     * @var array<int, string>
     */
    private const ALLOWED_MIME = [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/gif',
    ];

    /**
     * Blocked hosts for external URL registration (basic SSRF guard).
     * Private and loopback addresses must never be fetched.
     *
     * @var array<int, string>
     */
    private const BLOCKED_HOSTS = [
        'localhost',
        '127.0.0.1',
        '::1',
    ];

    /**
     * Private IP range prefixes (IPv4) that are disallowed for external URLs.
     *
     * @var array<int, string>
     */
    private const PRIVATE_IP_PREFIXES = [
        '10.',
        '172.16.', '172.17.', '172.18.', '172.19.',
        '172.20.', '172.21.', '172.22.', '172.23.',
        '172.24.', '172.25.', '172.26.', '172.27.',
        '172.28.', '172.29.', '172.30.', '172.31.',
        '192.168.',
        '169.254.',
    ];

    /**
     * Upload an image file and create a MediaAsset record for a product.
     *
     * @throws ValidationException If the file is not an allowed image type.
     */
    public function uploadForProduct(
        string $tenantId,
        string $productId,
        UploadedFile $file,
        ?string $userId,
    ): MediaAsset {
        $this->guardMimeType($file);

        // Generate a slot UUID for the storage path.  This UUID is used ONLY for the
        // S3 path — the asset's primary key is generated by Eloquent's HasUuids trait
        // (UUID v7) inside the transaction.  Both IDs are stable within the request.
        $slotId = (string) Str::uuid();
        $extension = $file->getClientOriginalExtension() ?: 'jpg';
        $path = sprintf('products/%s/%s/%s/original.%s', $tenantId, $productId, $slotId, $extension);

        // Compute checksum BEFORE the transaction while the temp file is accessible.
        $checksum = hash('sha256', (string) file_get_contents($file->getRealPath()));

        // Capture dimensions BEFORE the transaction (temp file must be accessible).
        [$width, $height] = getimagesize($file->getRealPath()) ?: [null, null];

        // 1. Store on S3 BEFORE the transaction so a committed DB row always has its file.
        $disk = Storage::disk('s3');
        $disk->putFileAs(dirname($path), $file, basename($path), 'private');

        try {
            /** @var MediaAsset $asset */
            $asset = DB::transaction(function () use (
                $tenantId,
                $path,
                $file,
                $checksum,
                $width,
                $height,
                $userId,
            ): MediaAsset {
                $asset = MediaAsset::create([
                    'tenant_id' => $tenantId,
                    'type' => MediaAssetType::Image,
                    'source' => MediaSource::Upload,
                    'status' => MediaStatus::Uploaded,
                    'storage_disk' => 's3',
                    'storage_path' => $path,
                    'mime_type' => $file->getMimeType(),
                    'file_size' => $file->getSize(),
                    'checksum' => $checksum,
                    'width' => $width,
                    'height' => $height,
                    'original_filename' => $file->getClientOriginalName(),
                    'uploaded_by' => $userId,
                ]);

                // Capture the Eloquent-generated asset ID for the after-commit closure.
                // (HasUuids generates a UUID v7 on insert — not the slot UUID used for the path.)
                $assetId = $asset->id;

                DB::afterCommit(function () use ($tenantId, $assetId): void {
                    GenerateRenditions::dispatch($tenantId, $assetId);
                });

                return $asset;
            });
        } catch (\Throwable $e) {
            // 2. Clean up the orphaned S3 object when the DB transaction fails.
            $disk->delete($path);
            throw $e;
        }

        return $asset;
    }

    /**
     * Register a third-party HTTPS image URL as a display-only MediaAsset.
     *
     * The URL is never fetched; it is stored verbatim and resolved at render-time.
     * Basic SSRF guards are applied: only HTTPS, length ≤ 2048, no private/loopback hosts.
     *
     * @throws ValidationException If the URL fails any safety check.
     */
    public function registerExternalUrl(
        string $tenantId,
        string $productId,
        string $url,
    ): MediaAsset {
        $this->guardExternalUrl($url);

        return MediaAsset::create([
            'tenant_id' => $tenantId,
            'type' => MediaAssetType::Image,
            'source' => MediaSource::ExternalUrl,
            'status' => MediaStatus::Ready,
            'storage_disk' => 'url',
            'external_url' => $url,
        ]);
    }

    /**
     * Assert that the uploaded file has an allowed image MIME type.
     *
     * This is the service-layer guard (layer 2); the presentation-layer guard is
     * {@see UploadMediaRequest} (layer 1).  Both must reject non-image types so
     * callers such as importers that bypass HTTP validation are still protected.
     *
     * @throws ValidationException
     */
    private function guardMimeType(UploadedFile $file): void
    {
        $mime = $file->getMimeType();

        if ($mime === null || ! in_array($mime, self::ALLOWED_MIME, true)) {
            throw ValidationException::withMessages([
                'image' => ['The file must be a valid image (JPEG, PNG, WebP, or GIF).'],
            ]);
        }
    }

    /**
     * Validate an external URL for SSRF-safety and structural correctness.
     *
     * Rules applied (in order):
     *  1. Must be parseable as a URL with a valid host.
     *  2. Scheme must be exactly "https".
     *  3. Total length must be ≤ 2048 characters.
     *  4. Host must not be localhost, 127.0.0.1, ::1, or any RFC-1918 / link-local prefix.
     *
     * @throws ValidationException
     */
    private function guardExternalUrl(string $url): void
    {
        $parsed = parse_url($url);

        if ($parsed === false || empty($parsed['host'])) {
            throw ValidationException::withMessages([
                'url' => ['The URL must be a valid absolute URL.'],
            ]);
        }

        if (($parsed['scheme'] ?? '') !== 'https') {
            throw ValidationException::withMessages([
                'url' => ['The URL must use the HTTPS scheme.'],
            ]);
        }

        if (strlen($url) > 2048) {
            throw ValidationException::withMessages([
                'url' => ['The URL must not exceed 2048 characters.'],
            ]);
        }

        // Normalize the host: strip IPv6 brackets so '[::1]' becomes '::1'
        // before comparing against BLOCKED_HOSTS.  parse_url() preserves the
        // brackets (RFC-3986 §3.2.2), so without trimming, the check misses
        // IPv6 loopback addresses passed as 'https://[::1]/path'.
        $host = strtolower(trim($parsed['host'], '[]'));

        if (in_array($host, self::BLOCKED_HOSTS, true)) {
            throw ValidationException::withMessages([
                'url' => ['The URL host is not allowed (blocked: loopback / localhost).'],
            ]);
        }

        foreach (self::PRIVATE_IP_PREFIXES as $prefix) {
            if (str_starts_with($host, $prefix)) {
                throw ValidationException::withMessages([
                    'url' => ['The URL host resolves to a private IP address and is not allowed.'],
                ]);
            }
        }
    }
}
