<?php

declare(strict_types=1);

return [
    'receipt' => 'Receipt',
    'tax_id' => 'Tax ID',
    'tel' => 'Tel',
    'receipt_no' => 'Receipt No.',
    'date_time' => 'Date/Time',
    'terminal' => 'Terminal',
    'cashier' => 'Cashier',
    'customer' => 'Customer',
    'discount' => 'Discount',
    'subtotal' => 'Subtotal',
    'tax' => 'Tax',
    'total' => 'TOTAL',
    'cash_rounding' => 'Cash Rounding',
    'vat_breakdown' => 'VAT Breakdown',
    'vat' => 'VAT',
    'base' => 'Base',
    'payment_methods' => 'Payment Methods',
    'card' => 'Card',
    'voucher' => 'Voucher',
    'change_given' => 'Change Given',
    'fiscal_information' => 'Fiscal Information',
    'chain_sequence' => 'Chain Sequence',
    'fiscal_hash' => 'Fiscal Hash',
    'previous_hash' => 'Previous Hash',
    'return_receipt' => 'RETURN',
    'original_receipt' => 'Original Receipt',
    'return_reason' => 'Reason',
    'duplicate_notice' => 'This is a duplicate copy — not valid as original',
    'thank_you' => 'Thank You!',
    'powered_by' => 'Powered by AutoERP',

    /*
     * Z-report (resources/views/pos/z-report.blade.php).
     *
     * The three `z_report_vat_*` disclosure keys are B-6(ii)/Option A1's own
     * strings. The rest of this block backfills keys the blade has referenced
     * since it was written but that no lang file ever defined — so the fiscal
     * PDF was literally printing `pos.z_report_gross_sales` to the customer.
     * Backfilled here rather than ticketed because otherwise the new VAT
     * disclosure would render as words beside neighbours rendering as dotted
     * keys. Additive only: no existing key is redefined.
     */
    'generated_by' => 'Generated by',
    'z_report' => 'Z Report',
    'z_report_number' => 'Report No.',
    'z_report_z_number' => 'Z Number',
    'z_report_genesis' => 'First Z report for this terminal (chain genesis)',
    'z_report_sales_summary' => 'Sales Summary',
    'z_report_receipt_count' => 'Receipts',
    'z_report_gross_sales' => 'Gross Sales',
    'z_report_net_sales' => 'Net Sales',
    'z_report_tax_amount' => 'VAT',
    'z_report_refunds' => 'Refunds',
    'z_report_voided' => 'Voided',
    'z_report_average_ticket' => 'Average Ticket',
    'z_report_cash_summary' => 'Cash Summary',
    'z_report_opening_cash' => 'Opening Cash',
    'z_report_expected_cash' => 'Expected Cash',
    'z_report_actual_cash' => 'Counted Cash',
    'z_report_variance' => 'Variance',
    'z_report_vat_rate' => 'Rate',
    'z_report_vat_net' => 'Net',
    'z_report_vat_amount' => 'VAT',
    'z_report_vat_gross' => 'Gross',
    'z_report_payment_method' => 'Method',
    'z_report_payment_count' => 'Count',
    'z_report_payment_amount' => 'Amount',

    // B-6(ii) — refund-VAT disclosure.
    'z_report_vat_on_sales' => 'VAT on sales',
    'z_report_vat_on_refunds' => 'VAT on refunds',
    'z_report_net_vat' => 'Net VAT',
    'z_report_vat_net_of_refunds' => 'net of refunds',
    'z_report_refund_vat_breakdown' => 'Refund VAT Breakdown',
    'z_report_vat_unreconciled' => 'VAT figures could not be reconciled for this period',
];
