/**
 * AutoERP Shared Types
 *
 * DO NOT edit — auto-generated by `php artisan typescript:transform`
 * (see CLAUDE.md rule #7 "Types flow from backend").
 *
 * Side-effect import registers the `declare global { … }` namespaces in
 * `generated.d.ts`. Import this package anywhere in apps/web to make
 * `App.Modules.*` and `App.Enums.*` visible to the compiler.
 */
import './generated'

export {}
