export { useVehicleWithCurrentOwner, fetchVehicleWithCurrentOwner } from './useVehicleWithCurrentOwner'
export type { VehicleWithCurrentOwner } from './useVehicleWithCurrentOwner'
export { usePartnerVehicles } from './usePartnerVehicles'
export { useVehicleOwnershipHistory } from './useVehicleOwnershipHistory'
export { useVehicleMileageHistory } from './useVehicleMileageHistory'
export { useLogVehicleMileage } from './useLogVehicleMileage'
export { useTransferVehicleOwnership } from './useTransferVehicleOwnership'
