<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * H2 backfill — restore document_lines.work_order_line_id for documents
     * generated by Workshop\WorkOrder\DocumentGenerationAdapter before the
     * fillable + copyLine() whitelist fix landed (Q2 2026 release).
     *
     * Strategy: for every Document row carrying a non-null work_order_id,
     * pair its DocumentLines (ordered by line_number) with the WO's
     * WorkOrderLines (ordered by display_order, excluding bundle-informational
     * children — same filter the adapter applies). Where the count matches
     * exactly, we update the FK column on each DocumentLine. We DO NOT
     * partial-match — a count mismatch indicates manual edits to either side
     * after generation, and a heuristic match would be unsafe.
     *
     * Idempotent: only updates rows where work_order_line_id IS NULL, so
     * re-running is a no-op once columns are populated.
     *
     * Pre-existing rows with explicit non-null work_order_line_id (e.g.
     * post-fix invoices) are left untouched.
     *
     * --- DO NOT RUN AUTOMATICALLY ---
     * This file lives under `database/migrations/manual/` so Laravel's
     * default migrator does NOT pick it up. Run explicitly when owner has
     * signed off:
     *
     *   php artisan migrate --path=database/migrations/manual/2026_04_28_120000_backfill_work_order_line_id_on_document_lines.php
     *
     * Reasons for the manual gate:
     *  - Touches signed Invoice rows; backfill writes a non-fiscal column,
     *    so the chain hash is invariant-safe (chain hashes only
     *    document_number | posted_at | total | currency per Spec §5.1), but
     *    a human review of the affected count is still warranted.
     *  - Heuristic match assumes 1:1 line ordering. Owner should confirm no
     *    manual line splits or merges happened on WO-originated documents
     *    before greenlight.
     */
    public function up(): void
    {
        // Pull every (document_id, work_order_id) pair where the document has
        // a WO origin and at least one line still missing its WO-line link.
        $pairs = DB::table('documents')
            ->join('document_lines', 'documents.id', '=', 'document_lines.document_id')
            ->whereNotNull('documents.work_order_id')
            ->whereNull('document_lines.work_order_line_id')
            ->select('documents.id as document_id', 'documents.work_order_id')
            ->distinct()
            ->get();

        foreach ($pairs as $pair) {
            $documentLines = DB::table('document_lines')
                ->where('document_id', $pair->document_id)
                ->orderBy('line_number')
                ->get(['id']);

            $workOrderLines = DB::table('workshop_work_order_lines')
                ->where('work_order_id', $pair->work_order_id)
                ->where('is_bundle_informational', false)
                ->orderBy('display_order')
                ->get(['id']);

            // Strict 1:1 match — a count mismatch means the document or the
            // WO was edited post-generation; refuse to guess.
            if ($documentLines->count() !== $workOrderLines->count()) {
                continue;
            }

            foreach ($documentLines as $idx => $dl) {
                $wol = $workOrderLines[$idx];
                DB::table('document_lines')
                    ->where('id', $dl->id)
                    ->whereNull('work_order_line_id')
                    ->update(['work_order_line_id' => $wol->id]);
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * Cannot distinguish backfilled rows from rows written by the adapter
     * post-fix. Safe rollback strategy: leave the column populated — the
     * fillable column drop already exists in the original
     * 2026_04_19_130005_add_work_order_references_to_documents migration.
     */
    public function down(): void
    {
        // Intentional no-op — see docblock.
    }
};
