<?php

declare(strict_types=1);

namespace Tests\Feature\Procurement;

use App\Enums\Vertical;
use App\Modules\Company\Domain\Company;
use App\Modules\Company\Domain\Enums\CompanyStatus;
use App\Modules\Company\Domain\UserCompanyMembership;
use App\Modules\Company\Services\CompanyContext;
use App\Modules\Document\Application\DTOs\DocumentData;
use App\Modules\Document\Domain\Document;
use App\Modules\Document\Domain\Enums\DocumentStatus;
use App\Modules\Document\Domain\Enums\DocumentType;
use App\Modules\Document\Domain\Enums\FiscalCategory;
use App\Modules\Document\Domain\Enums\FiscalStatus;
use App\Modules\Document\Domain\Enums\SupplierInvoiceMatchStatus;
use App\Modules\Identity\Domain\Enums\UserStatus;
use App\Modules\Identity\Domain\User;
use App\Modules\Partner\Domain\Enums\PartnerType;
use App\Modules\Partner\Domain\Partner;
use App\Modules\Product\Domain\Product;
use App\Modules\Procurement\Application\CreateRfqData;
use App\Modules\Procurement\Application\PurchaseQuoteRequestAwardService;
use App\Modules\Procurement\Application\PurchaseQuoteRequestService;
use App\Modules\Procurement\Application\UpdateRfqData;
use App\Modules\Tenant\Domain\Enums\SubscriptionPlan;
use App\Modules\Tenant\Domain\Enums\TenantStatus;
use App\Modules\Tenant\Domain\Tenant;
use Database\Seeders\RolesAndPermissionsSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use PHPUnit\Framework\Attributes\Test;
use Spatie\Permission\PermissionRegistrar;
use Tests\TestCase;

final class AutoGeneratedPurchaseOrderExposureTest extends TestCase
{
    use RefreshDatabase;

    private Tenant $tenant;

    private Company $company;

    private User $user;

    private Partner $supplier;

    protected function setUp(): void
    {
        parent::setUp();

        $this->tenant = Tenant::create([
            'name' => 'Auto PO Exposure Tenant',
            'slug' => 'auto-po-exposure-'.uniqid(),
            'status' => TenantStatus::Active,
            'plan' => SubscriptionPlan::Professional,
            'vertical' => Vertical::Parapharmacy,
        ]);

        $this->company = Company::create([
            'tenant_id' => $this->tenant->id,
            'name' => 'Auto PO Exposure Company',
            'country_code' => 'TN',
            'currency' => 'TND',
            'locale' => 'fr_TN',
            'timezone' => 'Africa/Tunis',
            'status' => CompanyStatus::Active,
        ]);

        app(PermissionRegistrar::class)->setPermissionsTeamId($this->tenant->id);
        $this->seed(RolesAndPermissionsSeeder::class);

        $this->user = User::create([
            'tenant_id' => $this->tenant->id,
            'name' => 'Auto PO Viewer',
            'email' => 'auto-po-viewer@example.com',
            'password' => bcrypt('password'),
            'status' => UserStatus::Active,
        ]);
        $this->user->assignRole('admin');

        UserCompanyMembership::create([
            'user_id' => $this->user->id,
            'company_id' => $this->company->id,
            'role' => 'admin',
        ]);

        app(CompanyContext::class)->setCompanyId($this->company->id);

        $this->supplier = Partner::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'name' => 'Auto PO Supplier',
            'type' => PartnerType::Supplier,
        ]);
    }

    #[Test]
    public function purchase_order_list_excludes_auto_generated_by_default_and_includes_them_on_opt_in(): void
    {
        $normal = $this->purchaseOrder('PO-NORMAL-001');
        $auto = $this->purchaseOrder('PO-AUTO-001', autoGenerated: true);

        $default = $this->actingAs($this->user, 'sanctum')->getJson('/api/v1/purchase-orders');
        $default->assertOk();
        $defaultIds = collect($default->json('data'))->pluck('id')->all();
        $this->assertContains($normal->id, $defaultIds);
        $this->assertNotContains($auto->id, $defaultIds);

        $withAuto = $this->actingAs($this->user, 'sanctum')->getJson('/api/v1/purchase-orders?include_auto_generated=1');
        $withAuto->assertOk();
        $withAutoRows = collect($withAuto->json('data'));
        $this->assertContains($normal->id, $withAutoRows->pluck('id')->all());
        $this->assertContains($auto->id, $withAutoRows->pluck('id')->all());
        $this->assertTrue($withAutoRows->firstWhere('id', $auto->id)['is_auto_generated']);
    }

    #[Test]
    public function auto_generated_purchase_order_detail_is_accessible_and_serialized_with_badge_flag(): void
    {
        $auto = $this->purchaseOrder('PO-AUTO-DETAIL-001', autoGenerated: true);

        $response = $this->actingAs($this->user, 'sanctum')->getJson("/api/v1/purchase-orders/{$auto->id}");

        $response->assertOk();
        $response->assertJsonPath('data.id', $auto->id);
        $response->assertJsonPath('data.is_auto_generated', true);

        $data = DocumentData::fromModel($auto, false)->toArray();
        $this->assertTrue($data['is_auto_generated']);
    }

    #[Test]
    public function document_chain_readers_include_auto_po_linked_supplier_invoices(): void
    {
        $auto = $this->purchaseOrder('PO-AUTO-CHAIN-001', autoGenerated: true);
        $invoice = $this->supplierInvoice('SI-AUTO-CHAIN-001', $auto);

        $poChain = $auto->getDocumentChain();
        $this->assertContains($invoice->id, $poChain['descendants']->pluck('id')->all());

        $siChain = $invoice->getDocumentChain();
        $this->assertContains($auto->id, $siChain['ancestors']->pluck('id')->all());
    }

    #[Test]
    public function auto_generated_po_for_same_supplier_does_not_trip_rfq_award_guard(): void
    {
        $product = Product::factory()->create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'name' => 'RFQ product',
        ]);
        $this->purchaseOrder('PO-AUTO-RFQ-001', autoGenerated: true);

        $rfqs = app(PurchaseQuoteRequestService::class)->createGroup(
            new CreateRfqData(
                partnerIds: [$this->supplier->id],
                lines: [[
                    'product_id' => $product->id,
                    'quantity' => '3.0000',
                    'unit_price' => null,
                    'description' => 'RFQ product',
                ]],
                validityDate: null,
                notes: null,
            ),
            $this->tenant->id,
            $this->company->id,
            $this->company->currency,
        );
        /** @var Document $rfq */
        $rfq = $rfqs->first();

        $responded = app(PurchaseQuoteRequestService::class)->recordResponse(
            $rfq->id,
            $this->tenant->id,
            $this->company->id,
            new UpdateRfqData(
                lines: [[
                    'id' => $rfq->lines->first()?->id,
                    'product_id' => $product->id,
                    'quantity' => '3.0000',
                    'unit_price' => '6.500',
                    'description' => 'RFQ product',
                ]],
                validityDate: null,
                supplierReference: null,
                leadTimeDays: null,
            ),
        );

        $awarded = app(PurchaseQuoteRequestAwardService::class)->award($responded->id, $this->tenant->id, $this->company->id);

        $this->assertSame(DocumentType::PurchaseOrder, $awarded->type);
        $this->assertSame($responded->id, $awarded->source_document_id);
    }

    private function purchaseOrder(string $number, bool $autoGenerated = false): Document
    {
        return Document::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'partner_id' => $this->supplier->id,
            'type' => DocumentType::PurchaseOrder,
            'fiscal_category' => FiscalCategory::NonFiscal,
            'fiscal_status' => FiscalStatus::Draft,
            'status' => DocumentStatus::Confirmed,
            'document_number' => $number,
            'document_date' => now()->toDateString(),
            'currency' => 'TND',
            'subtotal' => '20.000',
            'tax_amount' => '0.000',
            'total' => '20.000',
            'balance_due' => '20.000',
            'payload' => $autoGenerated ? [
                'auto_generated' => [
                    'source' => 'standalone_receipt',
                    'actor' => $this->user->id,
                    'created_at' => now()->toIso8601String(),
                ],
            ] : null,
        ]);
    }

    private function supplierInvoice(string $number, Document $purchaseOrder): Document
    {
        return Document::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'partner_id' => $this->supplier->id,
            'source_document_id' => $purchaseOrder->id,
            'type' => DocumentType::SupplierInvoice,
            'fiscal_category' => FiscalCategory::NonFiscal,
            'fiscal_status' => FiscalStatus::Draft,
            'status' => DocumentStatus::Draft,
            'document_number' => $number,
            'document_date' => now()->toDateString(),
            'currency' => 'TND',
            'subtotal' => '20.000',
            'tax_amount' => '0.000',
            'total' => '20.000',
            'balance_due' => '20.000',
            'match_status' => SupplierInvoiceMatchStatus::Matched,
            'payload' => [
                'supplier_invoice' => [
                    'source_document_ids' => [$purchaseOrder->id],
                ],
            ],
        ]);
    }
}
