<?php

declare(strict_types=1);

namespace App\Modules\Media\Application\Services;

use App\Modules\Media\Application\Jobs\GenerateRenditions;
use App\Modules\Media\Domain\Enums\MediaAssetType;
use App\Modules\Media\Domain\Enums\MediaOwnerType;
use App\Modules\Media\Domain\Enums\MediaSource;
use App\Modules\Media\Domain\Enums\MediaStatus;
use App\Modules\Media\Domain\Media\MediaAsset;
use App\Modules\Media\Domain\ValueObjects\ExternalUrlGuard;
use Illuminate\Database\QueryException;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use InvalidArgumentException;

/**
 * Service for uploading and registering media assets in the media subsystem.
 *
 * Entry points:
 *
 *  - {@see upload}: owner-agnostic upload for any {@see MediaOwnerType} and {@see MediaAssetType}.
 *  - {@see uploadForProduct}: product-image convenience wrapper delegating to {@see upload}.
 *  - {@see registerExternalUrl}: registers a third-party image URL (SSRF-safe, display-only).
 *
 * Upload flow:
 *  1. Validate MIME type against the caller-supplied allow-list.
 *  2. Compute SHA-256 checksum.
 *  3. Build deterministic storage path: {ownerType.segment}/{tenant}/{owner}/{slot}/original.{ext}
 *  4. PUT the file on S3 BEFORE the DB transaction (avoids a committed row pointing to a missing file).
 *     4a. If putFileAs() returns false (write failure), throw RuntimeException immediately —
 *         no DB row is created, no orphan is possible.
 *  5. Open a DB::transaction and create the MediaAsset row.
 *     - Images: status = UPLOADED (GenerateRenditions promotes to READY).
 *     - Non-images: status = READY immediately (no rendition pipeline; read-repo returns READY-only).
 *  6. After commit, dispatch GenerateRenditions ONLY for Image assets.
 *  7. On any Throwable, delete the orphaned S3 object and rethrow.
 */
final class MediaUploadService
{
    /**
     * Allowed MIME types for uploaded images.
     * Must stay in sync with UploadMediaRequest::rules() 'mimes:' list.
     *
     * @var array<int, string>
     */
    private const ALLOWED_MIME = [
        'image/jpeg',
        'image/png',
        'image/webp',
        'image/gif',
    ];

    /**
     * Alias for the image allow-list — used when delegating from uploadForProduct().
     *
     * @var array<int, string>
     */
    private const ALLOWED_IMAGE_MIME = self::ALLOWED_MIME;

    /**
     * Upload a file and create a MediaAsset record for the given owner.
     *
     * This is the generic, owner-agnostic entry point.  Callers pass the owner
     * type and ID explicitly; the storage path segment is derived from
     * {@see MediaOwnerType::storageSegment()}.
     *
     * Non-image assets (Document, Video …) are created with status = READY
     * immediately because only {@see GenerateRenditions} promotes Uploaded → Ready,
     * and that job is only dispatched for Image assets.  A Document left as
     * Uploaded would be invisible to every read query (which filters on Ready).
     *
     * @param  array<int, string>  $allowedMime  MIME types accepted for this upload.
     * @param  ?string  $sourceRef  Provenance identifier (e.g. the source URL an
     *                              enrichment pipeline scraped this asset from). When
     *                              non-null it is enforced unique per tenant by a
     *                              partial DB index, making re-ingestion idempotent.
     *
     * @throws ValidationException If the file MIME type is not in $allowedMime.
     * @throws QueryException If the row insert violates a DB
     *                        constraint (e.g. the partial-unique
     *                        `(tenant_id, source_ref)` idempotency
     *                        index when the same URL is ingested
     *                        concurrently).
     */
    public function upload(
        string $tenantId,
        MediaOwnerType $ownerType,
        string $ownerId,
        UploadedFile $file,
        ?string $userId,
        MediaAssetType $assetType,
        array $allowedMime,
        ?string $sourceRef = null,
    ): MediaAsset {
        $this->guardMimeTypeAgainst($file, $allowedMime);

        // Generate a slot UUID for the storage path.  This UUID is used ONLY for the
        // S3 path — the asset's primary key is generated by Eloquent's HasUuids trait
        // (UUID v7) inside the transaction.  Both IDs are stable within the request.
        $slotId = (string) Str::uuid();
        $extension = $file->getClientOriginalExtension() ?: 'bin';
        $path = sprintf(
            '%s/%s/%s/%s/original.%s',
            $ownerType->storageSegment(),
            $tenantId,
            $ownerId,
            $slotId,
            $extension,
        );

        // Compute checksum BEFORE the transaction while the temp file is accessible.
        $checksum = hash('sha256', (string) file_get_contents($file->getRealPath()));

        // Capture image dimensions only for Image assets (PDFs/videos have none).
        $width = null;
        $height = null;
        if ($assetType === MediaAssetType::Image) {
            [$width, $height] = getimagesize($file->getRealPath()) ?: [null, null];
        }

        // Store on S3 BEFORE the transaction so a committed DB row always has its file.
        // putFileAs() returns the stored path on success or false on failure; treat false
        // as a hard error so we never create an orphaned asset row pointing to a missing
        // object.  Throw BEFORE opening the transaction to keep the error boundary clean.
        $disk = Storage::disk('s3');
        $stored = $disk->putFileAs(dirname($path), $file, basename($path), 'private');

        if ($stored === false) {
            throw new \RuntimeException(
                "Object storage write failed — could not store file at '{$path}'. "
                .'Check S3/MinIO connectivity and bucket permissions before retrying.',
            );
        }

        // Non-images are created READY immediately; images start as UPLOADED and are
        // promoted to READY by the GenerateRenditions job after renditions are built.
        $initialStatus = $assetType === MediaAssetType::Image
            ? MediaStatus::Uploaded
            : MediaStatus::Ready;

        try {
            /** @var MediaAsset $asset */
            $asset = DB::transaction(function () use (
                $tenantId,
                $path,
                $file,
                $checksum,
                $width,
                $height,
                $userId,
                $assetType,
                $initialStatus,
                $sourceRef,
            ): MediaAsset {
                $asset = MediaAsset::create([
                    'tenant_id' => $tenantId,
                    'type' => $assetType,
                    'source' => MediaSource::Upload,
                    'status' => $initialStatus,
                    'storage_disk' => 's3',
                    'storage_path' => $path,
                    'mime_type' => $file->getMimeType(),
                    'file_size' => $file->getSize(),
                    'checksum' => $checksum,
                    'width' => $width,
                    'height' => $height,
                    'original_filename' => $file->getClientOriginalName(),
                    'uploaded_by' => $userId,
                    'source_ref' => $sourceRef,
                ]);

                // Dispatch rendition generation ONLY for image assets.
                if ($assetType === MediaAssetType::Image) {
                    $assetId = $asset->id;
                    DB::afterCommit(function () use ($tenantId, $assetId): void {
                        GenerateRenditions::dispatch($tenantId, $assetId);
                    });
                }

                return $asset;
            });
        } catch (\Throwable $e) {
            // Clean up the orphaned S3 object when the DB transaction fails.
            $disk->delete($path);
            throw $e;
        }

        return $asset;
    }

    /**
     * Upload an image file and create a MediaAsset record for a product.
     *
     * Delegates to {@see upload()} with Image asset type and the standard image
     * MIME allow-list.  Behavior is byte-identical to the previous implementation.
     *
     * @throws ValidationException If the file is not an allowed image type.
     * @throws QueryException If the row insert violates a DB
     *                        constraint (e.g. the partial-unique
     *                        `(tenant_id, source_ref)` index on a
     *                        concurrent re-ingestion of the same URL).
     */
    public function uploadForProduct(
        string $tenantId,
        string $productId,
        UploadedFile $file,
        ?string $userId,
        ?string $sourceRef = null,
    ): MediaAsset {
        return $this->upload(
            $tenantId,
            MediaOwnerType::Product,
            $productId,
            $file,
            $userId,
            MediaAssetType::Image,
            self::ALLOWED_IMAGE_MIME,
            $sourceRef,
        );
    }

    /**
     * Register a third-party HTTPS image URL as a display-only MediaAsset.
     *
     * The URL is never fetched; it is stored verbatim and resolved at render-time.
     * Basic SSRF guards are applied: only HTTPS, length ≤ 2048, no private/loopback hosts.
     *
     * @throws ValidationException If the URL fails any safety check.
     */
    public function registerExternalUrl(
        string $tenantId,
        string $productId,
        string $url,
    ): MediaAsset {
        $this->guardExternalUrl($url);

        return MediaAsset::create([
            'tenant_id' => $tenantId,
            'type' => MediaAssetType::Image,
            'source' => MediaSource::ExternalUrl,
            'status' => MediaStatus::Ready,
            'storage_disk' => 'url',
            'external_url' => $url,
        ]);
    }

    /**
     * Assert that the uploaded file's MIME type is in the given allow-list.
     *
     * This is the service-layer guard (layer 2); the presentation-layer guard is
     * the relevant FormRequest (layer 1).  Both must reject disallowed types so
     * callers such as importers that bypass HTTP validation are still protected.
     *
     * @param  array<int, string>  $allowedMime
     *
     * @throws ValidationException
     */
    private function guardMimeTypeAgainst(UploadedFile $file, array $allowedMime): void
    {
        $mime = $file->getMimeType();

        if ($mime === null || ! in_array($mime, $allowedMime, true)) {
            throw ValidationException::withMessages([
                'file' => [sprintf(
                    'The file MIME type "%s" is not allowed. Accepted: %s.',
                    (string) $mime,
                    implode(', ', $allowedMime),
                )],
            ]);
        }
    }

    /**
     * Validate an external URL for SSRF-safety and structural correctness.
     *
     * Rules applied (in order):
     *  1. Must be parseable as a URL with a valid host.
     *  2. Scheme must be exactly "https".
     *  3. Total length must be ≤ 2048 characters.
     *  4. Host must not be localhost, 127.0.0.1, ::1, or any RFC-1918 / link-local prefix.
     *
     * @throws ValidationException
     */
    private function guardExternalUrl(string $url): void
    {
        try {
            ExternalUrlGuard::assertHttpsHostAllowed($url);
        } catch (InvalidArgumentException $e) {
            throw ValidationException::withMessages([
                'url' => [$e->getMessage()],
            ]);
        }
    }
}
