<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            [
                'code' => 'TN',
                'name' => 'Tunisia',
                'native_name' => 'تونس',
                'currency_code' => 'TND',
                'currency_symbol' => 'د.ت',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+216',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_TN',
                'default_timezone' => 'Africa/Tunis',
                'is_active' => true,
                'tax_id_label' => 'Matricule Fiscal',
                'tax_id_regex' => '^[0-9]{7}[A-Z]{3}[0-9]{3}$',
            ],
            [
                'code' => 'FR',
                'name' => 'France',
                'native_name' => 'France',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+33',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_FR',
                'default_timezone' => 'Europe/Paris',
                'is_active' => true,
                'tax_id_label' => 'SIREN',
                'tax_id_regex' => '^[0-9]{9}$',
            ],

            // --- Europe ---
            [
                'code' => 'DE',
                'name' => 'Germany',
                'native_name' => 'Deutschland',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+49',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'de_DE',
                'default_timezone' => 'Europe/Berlin',
                'is_active' => true,
                'tax_id_label' => 'Steuernummer',
                'tax_id_regex' => '^\\d{10,11}$',
            ],
            [
                'code' => 'IT',
                'name' => 'Italy',
                'native_name' => 'Italia',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+39',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'it_IT',
                'default_timezone' => 'Europe/Rome',
                'is_active' => true,
                'tax_id_label' => 'Partita IVA',
                'tax_id_regex' => '^IT\\d{11}$',
            ],
            [
                'code' => 'ES',
                'name' => 'Spain',
                'native_name' => 'España',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+34',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'es_ES',
                'default_timezone' => 'Europe/Madrid',
                'is_active' => true,
                'tax_id_label' => 'NIF',
                'tax_id_regex' => '^[A-Z0-9]\\d{7}[A-Z0-9]$',
            ],
            [
                'code' => 'NL',
                'name' => 'Netherlands',
                'native_name' => 'Nederland',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+31',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'nl_NL',
                'default_timezone' => 'Europe/Amsterdam',
                'is_active' => true,
                'tax_id_label' => 'BTW-nummer',
                'tax_id_regex' => '^NL\\d{9}B\\d{2}$',
            ],
            [
                'code' => 'BE',
                'name' => 'Belgium',
                'native_name' => 'Belgique',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+32',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_BE',
                'default_timezone' => 'Europe/Brussels',
                'is_active' => true,
                'tax_id_label' => "Numéro d'entreprise",
                'tax_id_regex' => '^0\\d{9}$',
            ],
            [
                'code' => 'PT',
                'name' => 'Portugal',
                'native_name' => 'Portugal',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+351',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'pt_PT',
                'default_timezone' => 'Europe/Lisbon',
                'is_active' => true,
                'tax_id_label' => 'NIF',
                'tax_id_regex' => '^\\d{9}$',
            ],
            [
                'code' => 'AT',
                'name' => 'Austria',
                'native_name' => 'Österreich',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+43',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'de_AT',
                'default_timezone' => 'Europe/Vienna',
                'is_active' => true,
                'tax_id_label' => 'UID-Nummer',
                'tax_id_regex' => '^ATU\\d{8}$',
            ],
            [
                'code' => 'IE',
                'name' => 'Ireland',
                'native_name' => 'Ireland',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+353',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'en_IE',
                'default_timezone' => 'Europe/Dublin',
                'is_active' => true,
                'tax_id_label' => 'VAT Number',
                'tax_id_regex' => '^IE\\d{7}[A-Z]{1,2}$',
            ],
            [
                'code' => 'GR',
                'name' => 'Greece',
                'native_name' => 'Ελλάδα',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+30',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'el_GR',
                'default_timezone' => 'Europe/Athens',
                'is_active' => true,
                'tax_id_label' => 'ΑΦΜ',
                'tax_id_regex' => '^\\d{9}$',
            ],
            [
                'code' => 'FI',
                'name' => 'Finland',
                'native_name' => 'Suomi',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+358',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fi_FI',
                'default_timezone' => 'Europe/Helsinki',
                'is_active' => true,
                'tax_id_label' => 'Y-tunnus',
                'tax_id_regex' => '^\\d{7}-\\d$',
            ],
            [
                'code' => 'GB',
                'name' => 'United Kingdom',
                'native_name' => 'United Kingdom',
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+44',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'en_GB',
                'default_timezone' => 'Europe/London',
                'is_active' => true,
                'tax_id_label' => 'VAT Number',
                'tax_id_regex' => '^GB\\d{9}$',
            ],
            [
                'code' => 'CH',
                'name' => 'Switzerland',
                'native_name' => 'Schweiz',
                'currency_code' => 'CHF',
                'currency_symbol' => 'CHF',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+41',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'de_CH',
                'default_timezone' => 'Europe/Zurich',
                'is_active' => true,
                'tax_id_label' => 'UID',
                'tax_id_regex' => '^CHE-\\d{3}\\.\\d{3}\\.\\d{3}$',
            ],
            [
                'code' => 'SE',
                'name' => 'Sweden',
                'native_name' => 'Sverige',
                'currency_code' => 'SEK',
                'currency_symbol' => 'kr',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+46',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'sv_SE',
                'default_timezone' => 'Europe/Stockholm',
                'is_active' => true,
                'tax_id_label' => 'Organisationsnummer',
                'tax_id_regex' => '^\\d{6}-\\d{4}$',
            ],
            [
                'code' => 'PL',
                'name' => 'Poland',
                'native_name' => 'Polska',
                'currency_code' => 'PLN',
                'currency_symbol' => 'zł',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+48',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'pl_PL',
                'default_timezone' => 'Europe/Warsaw',
                'is_active' => true,
                'tax_id_label' => 'NIP',
                'tax_id_regex' => '^\\d{10}$',
            ],
            [
                'code' => 'RO',
                'name' => 'Romania',
                'native_name' => 'România',
                'currency_code' => 'RON',
                'currency_symbol' => 'lei',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+40',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ro_RO',
                'default_timezone' => 'Europe/Bucharest',
                'is_active' => true,
                'tax_id_label' => 'CUI',
                'tax_id_regex' => '^RO\\d{2,10}$',
            ],

            // --- MENA ---
            [
                'code' => 'SA',
                'name' => 'Saudi Arabia',
                'native_name' => 'المملكة العربية السعودية',
                'currency_code' => 'SAR',
                'currency_symbol' => 'ر.س',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+966',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_SA',
                'default_timezone' => 'Asia/Riyadh',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^3\\d{14}$',
            ],
            [
                'code' => 'AE',
                'name' => 'UAE',
                'native_name' => 'الإمارات',
                'currency_code' => 'AED',
                'currency_symbol' => 'د.إ',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+971',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_AE',
                'default_timezone' => 'Asia/Dubai',
                'is_active' => true,
                'tax_id_label' => 'TRN',
                'tax_id_regex' => '^\\d{15}$',
            ],
            [
                'code' => 'QA',
                'name' => 'Qatar',
                'native_name' => 'قطر',
                'currency_code' => 'QAR',
                'currency_symbol' => 'ر.ق',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+974',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_QA',
                'default_timezone' => 'Asia/Doha',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'KW',
                'name' => 'Kuwait',
                'native_name' => 'الكويت',
                'currency_code' => 'KWD',
                'currency_symbol' => 'د.ك',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+965',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_KW',
                'default_timezone' => 'Asia/Kuwait',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'BH',
                'name' => 'Bahrain',
                'native_name' => 'البحرين',
                'currency_code' => 'BHD',
                'currency_symbol' => '.د.ب',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+973',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_BH',
                'default_timezone' => 'Asia/Bahrain',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'OM',
                'name' => 'Oman',
                'native_name' => 'عُمان',
                'currency_code' => 'OMR',
                'currency_symbol' => 'ر.ع',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+968',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_OM',
                'default_timezone' => 'Asia/Muscat',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'JO',
                'name' => 'Jordan',
                'native_name' => 'الأردن',
                'currency_code' => 'JOD',
                'currency_symbol' => 'د.ا',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+962',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_JO',
                'default_timezone' => 'Asia/Amman',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'LB',
                'name' => 'Lebanon',
                'native_name' => 'لبنان',
                'currency_code' => 'LBP',
                'currency_symbol' => 'ل.ل',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+961',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_LB',
                'default_timezone' => 'Asia/Beirut',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'EG',
                'name' => 'Egypt',
                'native_name' => 'مصر',
                'currency_code' => 'EGP',
                'currency_symbol' => 'ج.م',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+20',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_EG',
                'default_timezone' => 'Africa/Cairo',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^\\d{9}$',
            ],
            [
                'code' => 'IQ',
                'name' => 'Iraq',
                'native_name' => 'العراق',
                'currency_code' => 'IQD',
                'currency_symbol' => 'ع.د',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+964',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_IQ',
                'default_timezone' => 'Asia/Baghdad',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'LY',
                'name' => 'Libya',
                'native_name' => 'ليبيا',
                'currency_code' => 'LYD',
                'currency_symbol' => 'د.ل',
                'currency_decimal_places' => 3,
                'phone_prefix' => '+218',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'ar_LY',
                'default_timezone' => 'Africa/Tripoli',
                'is_active' => true,
                'tax_id_label' => 'Tax Number',
                'tax_id_regex' => '^.{4,30}$',
            ],

            // --- Africa ---
            [
                'code' => 'MA',
                'name' => 'Morocco',
                'native_name' => 'المغرب',
                'currency_code' => 'MAD',
                'currency_symbol' => 'د.م.',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+212',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_MA',
                'default_timezone' => 'Africa/Casablanca',
                'is_active' => true,
                'tax_id_label' => 'ICE',
                'tax_id_regex' => '^\\d{15}$',
            ],
            [
                'code' => 'DZ',
                'name' => 'Algeria',
                'native_name' => 'الجزائر',
                'currency_code' => 'DZD',
                'currency_symbol' => 'د.ج',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+213',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_DZ',
                'default_timezone' => 'Africa/Algiers',
                'is_active' => true,
                'tax_id_label' => 'NIF',
                'tax_id_regex' => '^\\d{15}$',
            ],
            [
                'code' => 'SN',
                'name' => 'Senegal',
                'native_name' => 'Sénégal',
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'currency_decimal_places' => 0,
                'phone_prefix' => '+221',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_SN',
                'default_timezone' => 'Africa/Dakar',
                'is_active' => true,
                'tax_id_label' => 'NINEA',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'CI',
                'name' => "Côte d'Ivoire",
                'native_name' => "Côte d'Ivoire",
                'currency_code' => 'XOF',
                'currency_symbol' => 'CFA',
                'currency_decimal_places' => 0,
                'phone_prefix' => '+225',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_CI',
                'default_timezone' => 'Africa/Abidjan',
                'is_active' => true,
                'tax_id_label' => 'NCC',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'CM',
                'name' => 'Cameroon',
                'native_name' => 'Cameroun',
                'currency_code' => 'XAF',
                'currency_symbol' => 'FCFA',
                'currency_decimal_places' => 0,
                'phone_prefix' => '+237',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'fr_CM',
                'default_timezone' => 'Africa/Douala',
                'is_active' => true,
                'tax_id_label' => 'NIU',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'NG',
                'name' => 'Nigeria',
                'native_name' => 'Nigeria',
                'currency_code' => 'NGN',
                'currency_symbol' => '₦',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+234',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'en_NG',
                'default_timezone' => 'Africa/Lagos',
                'is_active' => true,
                'tax_id_label' => 'TIN',
                'tax_id_regex' => '^\\d{8}-\\d{4}$',
            ],
            [
                'code' => 'KE',
                'name' => 'Kenya',
                'native_name' => 'Kenya',
                'currency_code' => 'KES',
                'currency_symbol' => 'KSh',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+254',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'en_KE',
                'default_timezone' => 'Africa/Nairobi',
                'is_active' => true,
                'tax_id_label' => 'KRA PIN',
                'tax_id_regex' => '^[A-Z]\\d{9}[A-Z]$',
            ],
            [
                'code' => 'GH',
                'name' => 'Ghana',
                'native_name' => 'Ghana',
                'currency_code' => 'GHS',
                'currency_symbol' => 'GH₵',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+233',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'en_GH',
                'default_timezone' => 'Africa/Accra',
                'is_active' => true,
                'tax_id_label' => 'TIN',
                'tax_id_regex' => '^.{4,30}$',
            ],
            [
                'code' => 'ET',
                'name' => 'Ethiopia',
                'native_name' => 'ኢትዮጵያ',
                'currency_code' => 'ETB',
                'currency_symbol' => 'Br',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+251',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'am_ET',
                'default_timezone' => 'Africa/Addis_Ababa',
                'is_active' => true,
                'tax_id_label' => 'TIN',
                'tax_id_regex' => '^.{4,30}$',
            ],

            // --- Americas ---
            [
                'code' => 'US',
                'name' => 'United States',
                'native_name' => 'United States',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+1',
                'date_format' => 'MM/DD/YYYY',
                'default_locale' => 'en_US',
                'default_timezone' => 'America/New_York',
                'is_active' => true,
                'tax_id_label' => 'EIN',
                'tax_id_regex' => '^\\d{2}-\\d{7}$',
            ],
            [
                'code' => 'CA',
                'name' => 'Canada',
                'native_name' => 'Canada',
                'currency_code' => 'CAD',
                'currency_symbol' => '$',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+1',
                'date_format' => 'YYYY-MM-DD',
                'default_locale' => 'en_CA',
                'default_timezone' => 'America/Toronto',
                'is_active' => true,
                'tax_id_label' => 'BN',
                'tax_id_regex' => '^\\d{9}$',
            ],

            // --- Other ---
            [
                'code' => 'TR',
                'name' => 'Turkey',
                'native_name' => 'Türkiye',
                'currency_code' => 'TRY',
                'currency_symbol' => '₺',
                'currency_decimal_places' => 2,
                'phone_prefix' => '+90',
                'date_format' => 'DD/MM/YYYY',
                'default_locale' => 'tr_TR',
                'default_timezone' => 'Europe/Istanbul',
                'is_active' => true,
                'tax_id_label' => 'VKN',
                'tax_id_regex' => '^\\d{10}$',
            ],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']],
                $country
            );
        }
    }
}
