<?php

declare(strict_types=1);

namespace Tests\Feature\Accounting;

use App\Modules\Accounting\Application\Services\ChartOfAccountsService;
use App\Modules\Accounting\Application\Services\Reports\AgedPayablesService;
use App\Modules\Company\Domain\Company;
use App\Modules\Company\Domain\Enums\CompanyStatus;
use App\Modules\Company\Domain\Location;
use App\Modules\Company\Domain\UserCompanyMembership;
use App\Modules\Company\Services\CompanyContext;
use App\Modules\Document\Domain\Document;
use App\Modules\Document\Domain\DocumentLine;
use App\Modules\Document\Domain\Enums\DocumentStatus;
use App\Modules\Document\Domain\Enums\DocumentType;
use App\Modules\Document\Domain\Enums\FiscalCategory;
use App\Modules\Document\Domain\Enums\FiscalStatus;
use App\Modules\Document\Domain\Enums\SupplierInvoiceMatchStatus;
use App\Modules\Identity\Domain\Enums\UserStatus;
use App\Modules\Identity\Domain\User;
use App\Modules\Inventory\Domain\Enums\GoodsReceiptStatus;
use App\Modules\Inventory\Domain\GoodsReceipt;
use App\Modules\Inventory\Domain\GoodsReceiptLine;
use App\Modules\Partner\Domain\Enums\PartnerType;
use App\Modules\Partner\Domain\Partner;
use App\Modules\Procurement\Application\CreateSupplierInvoiceService;
use App\Modules\Procurement\Application\DTOs\StandaloneReceiptInput;
use App\Modules\Procurement\Application\DTOs\StandaloneReceiptLineInput;
use App\Modules\Procurement\Application\StandaloneReceiptService;
use App\Modules\Procurement\Application\SupplierInvoicePostingService;
use App\Modules\Procurement\Domain\Enums\BillControlMode;
use App\Modules\Procurement\Domain\Enums\MatchEnforcement;
use App\Modules\Procurement\Domain\Enums\MatchMode;
use App\Modules\Procurement\Domain\ProcurementPolicy;
use App\Modules\Product\Domain\Enums\ProductType;
use App\Modules\Product\Domain\Product;
use App\Modules\Tenant\Domain\Enums\SubscriptionPlan;
use App\Modules\Tenant\Domain\Enums\TenantStatus;
use App\Modules\Tenant\Domain\Tenant;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

final class AgedPayablesAutoPoTest extends TestCase
{
    use RefreshDatabase;

    private Tenant $tenant;

    private Company $company;

    private User $user;

    private Location $warehouse;

    private Partner $supplier;

    private Product $product;

    protected function setUp(): void
    {
        parent::setUp();

        $this->tenant = Tenant::create([
            'name' => 'Aged Payables Auto PO Tenant',
            'slug' => 'aged-payables-auto-po-'.Str::lower(Str::random(6)),
            'status' => TenantStatus::Active,
            'plan' => SubscriptionPlan::Professional,
        ]);
        $this->company = Company::create([
            'tenant_id' => $this->tenant->id,
            'name' => 'Aged Payables Auto PO Company',
            'country_code' => 'TN',
            'currency' => 'TND',
            'locale' => 'fr_TN',
            'timezone' => 'Africa/Tunis',
            'status' => CompanyStatus::Active,
        ]);
        $this->user = User::create([
            'tenant_id' => $this->tenant->id,
            'name' => 'Aged Payables Receiver',
            'email' => 'aged-payables-receiver@example.com',
            'password' => bcrypt('password'),
            'status' => UserStatus::Active,
        ]);
        UserCompanyMembership::create([
            'user_id' => $this->user->id,
            'company_id' => $this->company->id,
            'role' => 'admin',
        ]);
        app(CompanyContext::class)->setCompanyId($this->company->id);
        $this->warehouse = Location::create([
            'company_id' => $this->company->id,
            'code' => 'AGED-WH',
            'name' => 'Aged Payables Warehouse',
            'type' => 'warehouse',
            'is_active' => true,
            'is_default' => true,
        ]);
        $this->supplier = Partner::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'name' => 'Auto PO Payable Supplier',
            'type' => PartnerType::Supplier,
        ]);
        $this->product = Product::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'sku' => 'AGED-AUTO',
            'name' => 'Aged auto product',
            'type' => ProductType::Part,
            'is_active' => true,
            'is_physical' => true,
            'cost_price' => '0.000000',
        ]);
    }

    #[Test]
    public function normal_received_purchase_orders_do_not_appear_in_aged_payables(): void
    {
        $po = $this->createPurchaseOrder(autoGenerated: false, documentNumber: 'PO-NORMAL-RECEIVED');
        $poLine = $this->createPoLine($po, quantity: '4.0000', unitPrice: '5.000');
        $this->createPostedReceiptLine($po, $poLine, receivedQty: '4.0000', accrualUnitCost: '5.000000');

        $report = app(AgedPayablesService::class)->generate($this->company->id, Carbon::parse('2026-07-05'));

        $this->assertSame('0.0000', $report->grand_total);
        $this->assertCount(0, $report->lines);
    }

    #[Test]
    public function auto_po_with_posted_uninvoiced_receipt_appears_at_accrual_value(): void
    {
        $po = $this->createPurchaseOrder(autoGenerated: true, documentNumber: 'PO-AUTO-UNINVOICED');
        $poLine = $this->createPoLine($po, quantity: '5.0000', unitPrice: '7.250');
        $this->createPostedReceiptLine(
            $po,
            $poLine,
            receivedQty: '5.0000',
            accrualUnitCost: '7.250000',
            quantityInvoiced: '2.0000',
        );

        $report = app(AgedPayablesService::class)->generate($this->company->id, Carbon::parse('2026-07-05'));

        $this->assertSame('21.7500', $report->grand_total);
        $this->assertSame($this->supplier->id, $report->lines[0]->vendor_id);
        $this->assertSame('21.7500', $report->lines[0]->total);
    }

    #[Test]
    public function fully_invoiced_auto_po_receipt_drops_out_of_aged_payables(): void
    {
        $po = $this->createPurchaseOrder(autoGenerated: true, documentNumber: 'PO-AUTO-INVOICED');
        $poLine = $this->createPoLine($po, quantity: '5.0000', unitPrice: '7.250');
        $this->createPostedReceiptLine(
            $po,
            $poLine,
            receivedQty: '5.0000',
            accrualUnitCost: '7.250000',
            quantityInvoiced: '5.0000',
        );
        $poLine->forceFill(['quantity_invoiced' => '5.0000'])->save();

        $report = app(AgedPayablesService::class)->generate($this->company->id, Carbon::parse('2026-07-05'));

        $this->assertSame('0.0000', $report->grand_total);
        $this->assertCount(0, $report->lines);
    }

    #[Test]
    public function real_posted_supplier_invoice_clears_auto_po_receipt_from_aged_payables(): void
    {
        Carbon::setTestNow(Carbon::parse('2026-07-01 10:00:00'));

        try {
            app(ChartOfAccountsService::class)->seedForCompany($this->company);
            $this->allowReceiptFirst();

            $receiptResult = app(StandaloneReceiptService::class)->execute(new StandaloneReceiptInput(
                companyId: $this->company->id,
                supplierId: $this->supplier->id,
                locationId: $this->warehouse->id,
                actorId: $this->user->id,
                idempotencyKey: 'aged-payables-real-si-001',
                source: 'standalone_receipt',
                externalReference: 'BL-AGED-REAL-SI',
                externalDate: '2026-07-01',
                postImmediately: true,
                lines: [
                    new StandaloneReceiptLineInput(
                        productId: $this->product->id,
                        variantId: null,
                        quantity: '5.0000',
                        freeQuantity: '0.0000',
                        unitPrice: '7.250',
                    ),
                ],
            ));

            $purchaseOrder = $receiptResult->purchaseOrder->fresh(['lines']);
            $receipt = $receiptResult->receipt->fresh(['lines']);
            $this->assertNotNull($purchaseOrder);
            $this->assertNotNull($receipt);

            $before = app(AgedPayablesService::class)->generate($this->company->id, Carbon::parse('2026-07-05'));
            $this->assertSame('36.2500', $before->grand_total);

            /** @var DocumentLine $poLine */
            $poLine = $purchaseOrder->lines->sole();
            $invoice = app(CreateSupplierInvoiceService::class)->create([
                'partner_id' => $this->supplier->id,
                'source_document_id' => $purchaseOrder->id,
                'source_document_ids' => [$purchaseOrder->id],
                'currency' => 'TND',
                'issue_date' => '2026-07-02',
                'lines' => [[
                    'source_line_id' => $poLine->id,
                    'quantity' => '5.0000',
                    'unit_price' => '7.250',
                    'vat_rate' => '0.00',
                ]],
            ], $this->tenant->id, $this->company->id);

            app(SupplierInvoicePostingService::class)->post($invoice, $this->user->id);

            $this->assertSame(SupplierInvoiceMatchStatus::Matched, $invoice->fresh()->match_status);
            $this->assertSame('5.0000', DocumentLine::query()->findOrFail($poLine->id)->quantity_invoiced);
            $this->assertSame('5.0000', GoodsReceiptLine::query()->findOrFail($receipt->lines->sole()->id)->quantity_invoiced);

            $after = app(AgedPayablesService::class)->generate($this->company->id, Carbon::parse('2026-07-05'));
            $this->assertSame('0.0000', $after->grand_total);
            $this->assertCount(0, $after->lines);
        } finally {
            Carbon::setTestNow();
        }
    }

    private function createPurchaseOrder(bool $autoGenerated, string $documentNumber): Document
    {
        return Document::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'partner_id' => $this->supplier->id,
            'type' => DocumentType::PurchaseOrder,
            'fiscal_category' => FiscalCategory::NonFiscal,
            'fiscal_status' => FiscalStatus::Draft,
            'status' => DocumentStatus::Received,
            'document_number' => $documentNumber,
            'document_date' => '2026-07-01',
            'due_date' => '2026-07-31',
            'currency' => 'TND',
            'subtotal' => '36.250',
            'tax_amount' => '0.000',
            'total' => '36.250',
            'balance_due' => '36.250',
            'payload' => $autoGenerated ? [
                'auto_generated' => [
                    'source' => 'standalone_receipt',
                    'actor' => 'user-1',
                    'created_at' => '2026-07-01T10:00:00+00:00',
                ],
            ] : null,
        ]);
    }

    private function allowReceiptFirst(): void
    {
        ProcurementPolicy::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'bill_control_mode' => BillControlMode::Received,
            'match_mode' => MatchMode::ThreeWay,
            'match_enforcement' => MatchEnforcement::Warn,
            'variance_tolerance_percent' => '2.00',
            'variance_tolerance_max_amount' => '1.000',
            'allow_receipt_first' => true,
            'allow_invoice_first' => false,
            'invoice_first_requires_approval' => true,
        ]);
    }

    private function createPoLine(Document $po, string $quantity, string $unitPrice): DocumentLine
    {
        return DocumentLine::create([
            'document_id' => $po->id,
            'product_id' => $this->product->id,
            'product_code' => $this->product->sku,
            'line_number' => 1,
            'description' => $this->product->name,
            'quantity' => $quantity,
            'free_quantity' => '0.0000',
            'quantity_delivered' => '0.0000',
            'quantity_received' => $quantity,
            'free_quantity_received' => '0.0000',
            'quantity_invoiced' => '0.0000',
            'free_quantity_invoiced' => '0.0000',
            'unit_price' => $unitPrice,
            'tax_rate' => '0.00',
            'tax_amount' => '0.000',
            'line_total' => bcmul($quantity, $unitPrice, 3),
            'allocated_costs' => '0.000000',
            'landed_unit_cost' => $unitPrice.'000',
            'accrual_unit_cost' => $unitPrice.'000',
        ]);
    }

    private function createPostedReceiptLine(
        Document $po,
        DocumentLine $poLine,
        string $receivedQty,
        string $accrualUnitCost,
        string $quantityInvoiced = '0.0000',
    ): GoodsReceiptLine {
        $receipt = GoodsReceipt::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'purchase_order_id' => $po->id,
            'receipt_number' => 'GRN-AGED-'.Str::upper(Str::random(6)),
            'status' => GoodsReceiptStatus::Posted,
            'received_at' => now(),
        ]);

        return GoodsReceiptLine::create([
            'tenant_id' => $this->tenant->id,
            'company_id' => $this->company->id,
            'goods_receipt_id' => $receipt->id,
            'po_line_id' => $poLine->id,
            'product_id' => $this->product->id,
            'received_qty' => $receivedQty,
            'free_qty' => '0.0000',
            'received_unit_price' => null,
            'landed_unit_cost' => $accrualUnitCost,
            'accrual_unit_cost' => $accrualUnitCost,
            'effective_unit_cost' => $accrualUnitCost,
            'quantity_invoiced' => $quantityInvoiced,
            'free_quantity_invoiced' => '0.0000',
        ]);
    }
}
