<?php

declare(strict_types=1);

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\DB;
use Tests\Architecture\Support\EnumBackedColumnRegistry;
use Tests\Architecture\Support\EnumCheckParityAnalyzer;
use Tests\Architecture\Support\MigrationTableScopeMap;
use Tests\Architecture\Support\PgValueSetCheckReader;

/**
 * BOOTSTRAP-ONLY writer for the enum<->CHECK parity baseline AND the derived
 * register artifact.
 *
 *   DB_CONNECTION=pgsql DB_HOST=127.0.0.1 DB_PORT=5433 \
 *   DB_DATABASE=autoerp_<lane>_test DB_USERNAME=autoerp DB_PASSWORD=autoerp_secret \
 *   APP_ENV=testing CACHE_STORE=array \
 *   php tests/Architecture/Support/write-enum-check-parity-baseline.php
 *
 * The database it is pointed at MUST be a freshly migrated throwaway (the writer
 * refuses any name outside `autoerp_*test`): it reads the live `pg_constraint`
 * catalogue, so a half-migrated or hand-patched database writes a WRONG baseline.
 *
 * NOT part of CI and NOT part of any normal fix flow. The baseline is a
 * SHRINK-ONLY ratchet: entries leave it as the CHECK-adding batches close gaps,
 * and re-running this writer to ABSORB a new gap is not a fix — it is the exact
 * move the ratchet exists to stop. Growing the baseline is an owner decision on
 * the record.
 *
 * Writes two files:
 *   tests/Architecture/baselines/enum-check-parity-baseline.json  — the ratchet
 *   tests/Architecture/baselines/enum-check-parity-register.md    — the burn-down
 *                                                                   denominator
 */
$root = dirname(__DIR__, 3);
require $root.'/vendor/autoload.php';

/** @var Application $app */
$app = require $root.'/bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

$database = (string) DB::connection()->getDatabaseName();
if (DB::connection()->getDriverName() !== 'pgsql') {
    fwrite(STDERR, "[enum-check-parity] refusing to write a baseline from a non-PostgreSQL connection.\n");
    exit(2);
}
if (preg_match('/^autoerp_[a-z0-9_]*test$/', $database) !== 1) {
    fwrite(STDERR, "[enum-check-parity] refusing to read '{$database}': point this at a throwaway autoerp_*test database.\n");
    exit(2);
}

$scopes = new MigrationTableScopeMap($root.'/database/migrations');
$registry = new EnumBackedColumnRegistry($root.'/app', $scopes);
$analyzer = new EnumCheckParityAnalyzer;

$schemaColumns = [];
foreach (DB::select('SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = current_schema()') as $row) {
    /** @var object{table_name: string, column_name: string} $row */
    $schemaColumns[$row->table_name][] = $row->column_name;
}

$checks = (new PgValueSetCheckReader)->read(DB::connection());
$all = $registry->derive();
$tenant = $registry->deriveTenantScoped();

$findings = $analyzer->analyze($tenant, $checks, $schemaColumns);
$failures = $analyzer->failures($findings);

$keys = array_values(array_unique(array_column($failures, 'key')));
sort($keys, SORT_STRING);

$baselinePath = $root.'/tests/Architecture/baselines/enum-check-parity-baseline.json';
if (! is_dir(dirname($baselinePath))) {
    mkdir(dirname($baselinePath), 0o755, true);
}
file_put_contents($baselinePath, json_encode($keys, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n");

// ------------------------------------------------------------------ register --
$counts = [];
foreach ($findings as $finding) {
    $counts[$finding['verdict']] = ($counts[$finding['verdict']] ?? 0) + 1;
}
ksort($counts);

$statusNamed = array_values(array_filter($tenant, static fn (array $e): bool => str_ends_with($e['column'], 'status')));
$statusNamedKeys = array_fill_keys(array_map(static fn (array $e): string => $e['table'].'.'.$e['column'], $statusNamed), true);
$statusCovered = 0;
foreach ($findings as $finding) {
    if (isset($statusNamedKeys[$finding['table'].'.'.$finding['column']]) && $finding['verdict'] === EnumCheckParityAnalyzer::VERDICT_COVERED) {
        $statusCovered++;
    }
}

$lines = [];
$lines[] = '# Enum ↔ CHECK parity register — the slice-D burn-down denominator';
$lines[] = '';
$lines[] = '> GENERATED by `tests/Architecture/Support/write-enum-check-parity-baseline.php`. Do not hand-edit.';
$lines[] = '> Derived mechanically from model `$casts` (+ the `GOVERNED_AUDIT_COLUMNS` supplement) against a';
$lines[] = '> freshly migrated throwaway tenant database. Regenerate after any CHECK-adding batch.';
$lines[] = '';
$lines[] = sprintf('Generated: %s · schema: %d tenant tables · registry: %d enum-governed columns total.', date('Y-m-d'), count($scopes->map()), count($all));
$lines[] = '';
$lines[] = '## Denominator';
$lines[] = '';
$lines[] = '| Scope | Columns | Note |';
$lines[] = '|---|---:|---|';
$lines[] = sprintf('| tenant (ASSERTED) | %d | the gate\'s population |', count($tenant));
$lines[] = sprintf('| central (reported, NOT asserted) | %d | different migration path — out of scope for this gate |', count($all) - count($tenant));
$lines[] = '';
$lines[] = '| Verdict | Tenant columns |';
$lines[] = '|---|---:|';
foreach ($counts as $verdict => $count) {
    $lines[] = sprintf('| %s | %d |', $verdict, $count);
}
$lines[] = '';
$lines[] = sprintf('**Baseline size: %d.** That is the number that must go DOWN. `status`-suffixed columns: %d of %d covered.', count($keys), $statusCovered, count($statusNamed));
$lines[] = '';
$lines[] = '## Register — every enum-governed tenant column';
$lines[] = '';
$lines[] = '| Table | Column | Enum | Verdict | Baselined |';
$lines[] = '|---|---|---|---|---|';
$baselineSet = array_fill_keys($keys, true);
foreach ($findings as $finding) {
    $lines[] = sprintf(
        '| `%s` | `%s` | `%s` | %s | %s |',
        $finding['table'],
        $finding['column'],
        $finding['enum'],
        $finding['verdict'],
        isset($baselineSet[$finding['key']]) ? 'yes' : '—',
    );
}
$lines[] = '';
$lines[] = '## Divergences vs the §#26 hand census (2026-08-23 state-machine sweep)';
$lines[] = '';
$lines[] = 'The sweep put the population at **90 status columns, 76 uncovered, 14 constrained**. That census was';
$lines[] = 'grep-based over the migration tree and it is wrong in both directions. Recorded here because the';
$lines[] = 'burn-down denominator has to be the mechanical number, not the remembered one:';
$lines[] = '';
$lines[] = '- **It missed every `$table->enum()` column.** Laravel renders `enum()` on PostgreSQL as a varchar plus';
$lines[] = '  an auto-named `{table}_{column}_check`, which no grep for `ADD CONSTRAINT … CHECK` finds. So';
$lines[] = '  `pos_receipts.fiscal_status` (constrained since `tenant/2026_05_01_000001_prepare_pos_receipts_for_pending_seal.php`)';
$lines[] = '  and the whole `impersonation_*` family were filed as uncovered when they are covered.';
$lines[] = '- **It counted a different population.** The register above is every column an `app/**/Domain/Enums/*`';
$lines[] = '  enum GOVERNS, not every column named `*status*`: 244 tenant columns, not 90. Restricted to';
$lines[] = '  `*status`-suffixed columns the count is 74, of which 15 are covered — close to the sweep\'s 76/14 but';
$lines[] = '  not equal, and the gap is columns with no enum cast at all (below).';
$lines[] = '- **`bank_reconciliations.status` cannot be asserted at all.** The table carries';
$lines[] = '  `bank_reconciliations_status_check` but has NO Eloquent model, so there is no enum to compare it to.';
$lines[] = '  The sweep counted it among the 14 constrained; this gate cannot see it. Same class:';
$lines[] = '  `fiscal_event_quarantine.payload_parse_status` is `$fillable` and documented `string|null` while its';
$lines[] = '  sibling `fiscal_events.payload_parse_status` IS cast — a missing cast, not a missing CHECK.';
$lines[] = '- **One column is already DIVERGENT, not merely uncovered:** see the NARROWER row above. A CHECK that';
$lines[] = '  is narrower than its enum is a write bomb, not debt.';
$lines[] = '';
$lines[] = '## Central-database columns (reported, never asserted)';
$lines[] = '';
$lines[] = '| Table | Column | Enum | Has value-set CHECK |';
$lines[] = '|---|---|---|---|';
foreach ($all as $entry) {
    if ($entry['scope'] === MigrationTableScopeMap::SCOPE_TENANT) {
        continue;
    }
    $lines[] = sprintf(
        '| `%s` | `%s` | `%s` | %s |',
        $entry['table'],
        $entry['column'],
        $entry['enum'],
        isset($checks[$entry['table']][$entry['column']]) ? 'yes' : 'NO',
    );
}
$lines[] = '';

file_put_contents($root.'/tests/Architecture/baselines/enum-check-parity-register.md', implode("\n", $lines));

fwrite(STDERR, sprintf(
    "[enum-check-parity] %d tenant columns, %d baseline entries written; verdicts: %s\n",
    count($tenant),
    count($keys),
    json_encode($counts),
));
