// This file is generated. Do not edit it by hand.
// Source: apps/api/database/seeders/RolesAndPermissionsSeeder.php
// Source hash: sha256:2578583cb8d8ca55e7c3f07e2e84eca751caee49d76060f67a81dc19a42f9649

export const PERMISSIONS = {
  'accounts.manage': ['accountant', 'admin', 'manager'],
  'accounts.view': ['accountant', 'admin', 'manager', 'viewer'],
  'audit.view': ['accountant', 'admin'],
  'bank-statements.import': ['accountant', 'admin'],
  'bank-statements.reconcile': ['accountant', 'admin'],
  'bank-statements.reopen': ['admin'],
  'bank-statements.view': ['accountant', 'admin'],
  'batches.create': ['admin', 'manager'],
  'batches.delete': ['admin', 'manager'],
  'batches.recall': ['admin', 'manager'],
  'batches.traceability': ['admin', 'manager'],
  'batches.update': ['admin', 'manager'],
  'batches.view': ['admin', 'cashier', 'manager'],
  'batches.write-off': ['admin', 'manager'],
  'catalog.attributes.create': ['admin', 'manager'],
  'catalog.attributes.delete': ['admin', 'manager'],
  'catalog.attributes.update': ['admin', 'manager'],
  'catalog.attributes.view': ['admin', 'manager'],
  'catalog.labels.print': ['admin', 'manager'],
  'catalog.variants.create': ['admin', 'manager'],
  'catalog.variants.delete': ['admin', 'manager'],
  'catalog.variants.update': ['admin', 'manager'],
  'catalog.variants.view': ['admin', 'manager'],
  'catalog_cart.convert_po': ['admin', 'manager'],
  'catalog_cart.convert_so': ['admin', 'manager'],
  'catalog_cart.create': ['admin', 'manager', 'operator'],
  'catalog_cart.manage_all': ['admin'],
  'catalog_cart.marketplace_checkout': ['admin', 'manager'],
  'catalog_cart.view': ['admin', 'cashier', 'manager', 'operator', 'viewer'],
  'compliance.export_jet': ['accountant', 'admin', 'manager'],
  'compliance.verify_chains': ['accountant', 'admin', 'manager'],
  'compliance.view_reprint_log': ['accountant', 'admin', 'manager'],
  'composite-items.create': ['admin', 'manager'],
  'composite-items.delete': ['admin', 'manager'],
  'composite-items.manage-recipes': ['admin', 'manager'],
  'composite-items.update': ['admin', 'manager'],
  'composite-items.view': ['admin', 'cashier', 'manager', 'viewer'],
  'contacts.create': ['admin', 'cashier', 'manager'],
  'contacts.delete': ['admin', 'manager'],
  'contacts.update': ['admin', 'manager'],
  'contacts.view': ['admin', 'cashier', 'manager'],
  'coupons.manage': ['admin', 'manager'],
  'coupons.view': ['admin', 'manager', 'viewer'],
  'credit-notes.create': ['admin', 'manager'],
  'credit-notes.post': ['accountant', 'admin', 'manager'],
  'credit-notes.view': ['accountant', 'admin', 'manager', 'viewer'],
  'dashboard.owner': ['admin', 'manager'],
  'deliveries.confirm': ['admin', 'manager'],
  'deliveries.create': ['admin', 'manager', 'operator'],
  'deliveries.delete': ['admin', 'manager'],
  'deliveries.edit': ['admin', 'manager', 'operator'],
  'deliveries.view': ['admin', 'cashier', 'manager', 'operator', 'viewer'],
  'document-ingestions.commit': ['accountant', 'admin', 'manager'],
  'document-ingestions.create': ['accountant', 'admin', 'manager'],
  'document-ingestions.reject': ['accountant', 'admin', 'manager'],
  'document-ingestions.view': ['accountant', 'admin', 'manager'],
  'documents.update': ['accountant', 'admin', 'cashier', 'manager', 'operator'],
  'documents.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'enrichment.review': ['admin', 'manager'],
  'enrichment.submit': ['admin', 'manager'],
  'enrichment.view': ['admin', 'manager'],
  'expense-categories.create': ['accountant', 'admin', 'manager'],
  'expense-categories.delete': ['accountant', 'admin', 'manager'],
  'expense-categories.update': ['accountant', 'admin', 'manager'],
  'expense-categories.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'expense-recurrences.create': ['accountant', 'admin', 'manager'],
  'expense-recurrences.delete': ['accountant', 'admin', 'manager'],
  'expense-recurrences.update': ['accountant', 'admin', 'manager'],
  'expense-recurrences.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'expenses.create': ['accountant', 'admin', 'cashier', 'manager', 'operator'],
  'expenses.delete': ['accountant', 'admin'],
  'expenses.export': ['accountant', 'admin', 'manager'],
  'expenses.pay': ['accountant', 'admin', 'manager'],
  'expenses.post': ['accountant', 'admin', 'manager'],
  'expenses.update': ['accountant', 'admin', 'manager', 'operator'],
  'expenses.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'fiscal.events.resolve_quarantine': ['admin'],
  'fiscal.events.verify_chain': ['admin'],
  'fiscal.refunds.manage_dead_letters': ['admin', 'manager'],
  'fraud-alerts.manage': ['admin', 'manager'],
  'fraud-alerts.view': ['accountant', 'admin', 'manager'],
  'fraud-settings.update': ['admin', 'manager'],
  'fraud-settings.view': ['accountant', 'admin', 'manager'],
  'goods-receipt.create-standalone': ['admin', 'manager'],
  'goods-receipt.edit-price': ['admin', 'manager'],
  'imports.manage': ['admin'],
  'income.create': ['accountant', 'admin', 'cashier', 'manager', 'operator'],
  'income.delete': ['accountant', 'admin'],
  'income.post': ['accountant', 'admin', 'manager'],
  'income.update': ['accountant', 'admin', 'manager', 'operator'],
  'income.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'instruments.bounce': ['accountant', 'admin', 'manager'],
  'instruments.cancel': ['accountant', 'admin', 'manager'],
  'instruments.cancel-outbound': ['accountant', 'admin'],
  'instruments.clear': ['accountant', 'admin', 'manager'],
  'instruments.clear-outbound': ['accountant', 'admin'],
  'instruments.create': ['admin', 'cashier', 'manager'],
  'instruments.remit': ['accountant', 'admin', 'manager'],
  'instruments.transfer': ['accountant', 'admin', 'manager'],
  'instruments.update': ['accountant', 'admin', 'manager'],
  'instruments.view': ['accountant', 'admin', 'cashier', 'manager', 'viewer'],
  'inventory.adjust': ['admin', 'manager'],
  'inventory.receive': ['admin', 'manager'],
  'inventory.transfer': ['admin', 'manager'],
  'inventory.transfers.cancel': ['admin', 'manager'],
  'inventory.transfers.complete': ['admin', 'manager'],
  'inventory.transfers.create': ['admin', 'manager'],
  'inventory.transfers.view': ['admin', 'manager'],
  'inventory.view': ['admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'invoices.cancel': ['admin'],
  'invoices.create': ['admin', 'cashier', 'manager', 'operator'],
  'invoices.delete': ['admin'],
  'invoices.post': ['accountant', 'admin', 'manager'],
  'invoices.print': ['admin', 'cashier', 'manager', 'operator'],
  'invoices.update': ['admin', 'manager'],
  'invoices.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'journal.create': ['accountant', 'admin'],
  'journal.post': ['accountant', 'admin'],
  'journal.view': ['accountant', 'admin', 'manager', 'viewer'],
  'ledger.view': ['accountant', 'admin'],
  'loyalty.enroll': ['admin', 'cashier', 'manager'],
  'loyalty.manage': ['admin', 'manager'],
  'loyalty.view': ['admin', 'manager', 'viewer'],
  'marketplace.admin': ['admin'],
  'marketplace.browse': ['admin', 'cashier', 'manager', 'operator', 'viewer'],
  'marketplace.order': ['admin', 'manager'],
  'marketplace.view_orders': ['admin', 'manager'],
  'menus.manage': ['admin', 'manager'],
  'menus.view': ['admin', 'cashier', 'manager', 'viewer'],
  'modifier-groups.manage': ['admin', 'manager'],
  'modifier-groups.view': ['admin', 'cashier', 'manager', 'viewer'],
  'orders.confirm': ['admin', 'manager'],
  'orders.create': ['admin', 'manager', 'operator'],
  'orders.delete': ['admin'],
  'orders.update': ['admin', 'manager', 'operator'],
  'orders.view': ['admin', 'cashier', 'manager', 'operator', 'viewer'],
  'partners.create': ['admin', 'cashier', 'manager', 'operator'],
  'partners.delete': ['admin'],
  'partners.update': ['admin', 'manager', 'operator'],
  'partners.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'payments.allocate': ['accountant', 'admin', 'manager'],
  'payments.create': ['accountant', 'admin', 'cashier', 'manager', 'operator'],
  'payments.refund': ['accountant', 'admin', 'manager'],
  'payments.reverse': ['admin'],
  'payments.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'viewer'],
  'payments.void': ['admin'],
  'pos.approve_account_status_override': ['admin', 'manager'],
  'pos.approve_cash_drawer_control': ['admin', 'manager'],
  'pos.approve_credit_limit_override': ['admin', 'manager'],
  'pos.approve_discount_limit_override': ['admin', 'manager'],
  'pos.approve_tender_tolerance_override': ['admin', 'manager'],
  'pos.approve_void_or_return_override': ['admin', 'manager'],
  'pos.audit_sync': ['admin', 'cashier', 'manager'],
  'pos.close_shift_with_variance': ['admin', 'manager'],
  'pos.configure_cash_count': ['admin', 'manager'],
  'pos.extend_voucher_expiry': ['admin', 'manager'],
  'pos.fiscal_schema_cutover': ['admin'],
  'pos.generate_z_report': ['admin', 'cashier', 'manager'],
  'pos.issue_goodwill_voucher': ['admin', 'manager'],
  'pos.issue_goodwill_voucher_high_value': ['admin'],
  'pos.manage_shifts': ['admin', 'cashier', 'manager'],
  'pos.manage_tables': ['admin', 'manager'],
  'pos.manage_terminals': ['admin', 'manager'],
  'pos.operate_terminal': ['admin', 'cashier', 'manager'],
  'pos.process_returns': ['admin', 'manager'],
  'pos.redeem_voucher': ['admin', 'cashier', 'manager'],
  'pos.refund_above_threshold': ['admin', 'manager'],
  'pos.refund_destination_override': ['admin', 'manager'],
  'pos.refund_extend_daily_cap': ['admin', 'manager'],
  'pos.refund_no_receipt': ['admin', 'manager'],
  'pos.refund_voucher_to_cash': ['admin', 'manager'],
  'pos.rotate_qr_signing_key': ['admin'],
  'pos.search_customer_cross_company': ['admin'],
  'pos.search_customer_full_history': ['admin', 'manager'],
  'pos.search_customer_recent_purchases': ['admin', 'cashier', 'manager'],
  'pos.tolerance.apply': ['admin', 'cashier', 'manager'],
  'pos.transfer_voucher': ['admin'],
  'pos.view_cross_location_stock': ['admin', 'manager'],
  'pos.view_receipts': ['admin', 'cashier', 'manager'],
  'pos.view_reports': ['admin', 'manager'],
  'pos.void_receipts': ['admin', 'manager'],
  'pos.void_voucher': ['admin', 'manager'],
  'pos_held_orders.create': ['admin', 'cashier', 'manager'],
  'pos_held_orders.delete': ['admin', 'cashier', 'manager'],
  'pos_held_orders.view': ['admin', 'cashier', 'manager'],
  'pos_orders.create': ['admin', 'cashier', 'manager'],
  'pos_orders.delete': ['admin', 'manager'],
  'pos_orders.update': ['admin', 'cashier', 'manager'],
  'pos_orders.view': ['admin', 'cashier', 'manager'],
  'pricing.manage': ['admin', 'manager'],
  'pricing.sell_below_cost': ['admin', 'manager'],
  'pricing.sell_below_minimum_margin': ['admin', 'manager'],
  'pricing.sell_below_target_margin': ['admin', 'manager'],
  'pricing.view': ['admin', 'manager', 'viewer'],
  'pricing.view_cost_prices': ['admin', 'manager'],
  'products.create': ['admin', 'manager'],
  'products.delete': ['admin'],
  'products.import': ['admin', 'manager'],
  'products.update': ['admin', 'manager'],
  'products.view': ['admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'promotions.manage': ['admin', 'manager'],
  'promotions.view': ['admin', 'manager', 'viewer'],
  'purchase-orders.confirm': ['admin', 'manager'],
  'purchase-orders.create': ['admin', 'manager', 'operator'],
  'purchase-orders.delete': ['admin'],
  'purchase-orders.receive': ['admin', 'manager'],
  'purchase-orders.update': ['admin', 'manager', 'operator'],
  'purchase-orders.view': ['admin', 'manager', 'operator', 'viewer'],
  'purchase-quote-requests.convert': ['admin', 'manager'],
  'purchase-quote-requests.create': ['admin', 'manager'],
  'purchase-quote-requests.delete': ['admin', 'manager'],
  'purchase-quote-requests.update': ['admin', 'manager'],
  'purchase-quote-requests.view': ['admin', 'manager', 'operator', 'viewer'],
  'quotes.convert': ['admin', 'manager'],
  'quotes.create': ['admin', 'cashier', 'manager', 'operator'],
  'quotes.delete': ['admin'],
  'quotes.update': ['admin', 'manager', 'operator'],
  'quotes.view': ['admin', 'cashier', 'manager', 'operator', 'viewer'],
  'replenishment.create': ['admin', 'manager', 'operator'],
  'replenishment.process': ['admin', 'manager'],
  'replenishment.view': ['admin', 'manager', 'operator'],
  'reports.financial': ['accountant', 'admin'],
  'reports.manage': ['accountant', 'admin'],
  'reports.operational': ['accountant', 'admin', 'manager'],
  'reports.view': ['admin'],
  'repositories.manage': ['accountant', 'admin'],
  'repositories.view': ['accountant', 'admin', 'manager', 'viewer'],
  'roles.manage': ['admin'],
  'roles.view': ['admin'],
  'scheduling.appointments.cancel': ['admin', 'manager', 'operator'],
  'scheduling.appointments.convert': ['admin', 'manager'],
  'scheduling.appointments.create': ['admin', 'manager', 'operator'],
  'scheduling.appointments.update': ['admin', 'manager', 'operator'],
  'scheduling.appointments.view': ['accountant', 'admin', 'manager', 'operator', 'technician'],
  'scheduling.bays.manage': ['admin', 'manager'],
  'scheduling.bays.view': ['accountant', 'admin', 'manager', 'operator', 'technician'],
  'settings.manage': ['admin', 'manager'],
  'settings.update': ['admin'],
  'settings.view': ['admin', 'manager', 'viewer'],
  'supplier-invoices.approve-invoice-first': ['accountant', 'admin', 'manager'],
  'supplier-invoices.create-pending': ['accountant', 'admin', 'manager'],
  'supplier-invoices.link-receipts': ['accountant', 'admin', 'manager'],
  'taxation.tax_configurations.manage': ['accountant', 'admin'],
  'treasury.adjust': ['accountant', 'admin', 'manager'],
  'treasury.manage': ['accountant', 'admin'],
  'treasury.transfer': ['accountant', 'admin', 'manager'],
  'treasury.view': ['accountant', 'admin', 'manager'],
  'uom.create': ['admin', 'manager'],
  'uom.delete': ['admin', 'manager'],
  'uom.edit': ['admin', 'manager'],
  'uom.view': ['admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'users.assign-roles': ['admin'],
  'users.create': ['admin'],
  'users.delete': ['admin'],
  'users.manage_location_access': ['admin'],
  'users.update': ['admin'],
  'users.view': ['admin', 'manager'],
  'vehicles.create': ['admin', 'manager', 'operator'],
  'vehicles.delete': ['admin'],
  'vehicles.log_mileage': ['admin', 'manager', 'operator', 'technician'],
  'vehicles.manage_ownership': ['admin', 'manager', 'operator'],
  'vehicles.update': ['admin', 'manager', 'operator'],
  'vehicles.view': ['admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'withholding.create': ['accountant', 'admin'],
  'withholding.delete': ['admin'],
  'withholding.update': ['accountant', 'admin'],
  'withholding.view': ['accountant', 'admin', 'manager'],
  'work-orders.approve': ['admin', 'manager'],
  'work-orders.assign': ['admin', 'manager'],
  'work-orders.cancel': ['admin', 'manager'],
  'work-orders.complete': ['admin', 'manager', 'operator', 'technician'],
  'work-orders.create': ['admin', 'manager', 'operator'],
  'work-orders.transition': ['admin', 'manager', 'operator'],
  'work-orders.update': ['admin', 'manager', 'operator', 'technician'],
  'work-orders.view': ['accountant', 'admin', 'cashier', 'manager', 'operator', 'technician', 'viewer'],
  'work-orders.view_financials': ['accountant', 'admin', 'manager'],
  'workshop-bundles.manage': ['admin', 'manager', 'operator'],
  'workshop-bundles.view': ['admin', 'manager', 'operator', 'technician'],
  'workshop.payroll.generate': ['admin', 'manager'],
  'workshop.payroll.view': ['admin', 'manager'],
  'workshop.technicians.adjust_time_entries': ['admin', 'manager'],
  'workshop.technicians.approve_time_off': ['admin', 'manager'],
  'workshop.technicians.manage': ['admin', 'manager'],
  'workshop.technicians.manage_certifications': ['admin', 'manager'],
  'workshop.technicians.manage_time_entries': ['admin', 'manager', 'technician'],
  'workshop.technicians.manage_time_off': ['admin', 'manager'],
  'workshop.technicians.view': ['admin', 'manager', 'operator', 'technician'],
  'workshop.technicians.view_pay': ['admin', 'manager'],
  'workshop.technicians.view_pii': ['admin', 'manager'],
} as const

export type Permission = keyof typeof PERMISSIONS
