<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\BroadcastServiceProvider::class,
    App\Providers\EventServiceProvider::class,
    App\Modules\Identity\Infrastructure\Providers\IdentityServiceProvider::class,
    App\Modules\Tenant\Infrastructure\Providers\TenantServiceProvider::class,
    App\Modules\Company\CompanyServiceProvider::class,
    App\Modules\Partner\PartnerServiceProvider::class,
    App\Modules\Product\ProductServiceProvider::class,
    App\Modules\Vehicle\Providers\VehicleServiceProvider::class,
    App\Modules\Document\Providers\DocumentServiceProvider::class,
    App\Modules\Accounting\Providers\AccountingServiceProvider::class,
    App\Modules\Inventory\Providers\InventoryServiceProvider::class,
    App\Modules\BatchExpiry\BatchExpiryServiceProvider::class,
    App\Modules\Treasury\Providers\TreasuryServiceProvider::class,
    App\Modules\Compliance\Providers\ComplianceServiceProvider::class,
    App\Modules\Import\Providers\ImportServiceProvider::class,
    App\Modules\Dashboard\Providers\DashboardServiceProvider::class,
    App\Modules\Media\MediaServiceProvider::class,
    App\Modules\Pricing\Providers\PricingServiceProvider::class,
    App\Modules\Service\Providers\ServiceModuleServiceProvider::class,
    App\Modules\Billing\Providers\BillingServiceProvider::class,
    App\Modules\Expense\Providers\ExpenseServiceProvider::class,
    App\Modules\Taxation\Providers\TaxationServiceProvider::class,
];
