/**
 * `refund_intents` — v3-refund-chain-integration spec §4.4/§4.5/§4.6.
 *
 * The durable, DEVICE-LOCAL, pre-signing intent/approval/payout-
 * reconciliation state machine for a v4 refund. Narrowed scope since
 * spec §7's ruling (Revision 4): this table is NOT the Z/expected-cash
 * source of truth — `offline_receipts.receipt_kind='refund'` rows are
 * (a separate item's job). This repository owns only the intent
 * lifecycle: `drafted -> approval_authored -> refund_event_appended ->
 * synced` (terminal for local purposes, §4.6 -- the device never claims
 * knowledge of server-side projection success/failure), or
 * `-> dead_lettered_local` (the append itself permanently failed, no
 * fiscal event exists) or `-> abandoned`.
 */

import type Database from '@tauri-apps/plugin-sql';
import { execute, queryAll, queryOne } from '@/lib/db';
import { sha256 } from '@/lib/fiscal/hashService';
import { bcadd } from '@/lib/decimal';

/** quantity scale (rule 19's device-side QuantityScale convention). */
const QUANTITY_SCALE = 4;

export const REFUND_INTENT_STATES = [
  'drafted',
  'approval_authored',
  'refund_event_appended',
  'synced',
  'dead_lettered_local',
  'abandoned',
] as const;

export type RefundIntentState = (typeof REFUND_INTENT_STATES)[number];

/** Spec §4.4 Revision 4 fold-item-7 fix -- the ONLY states a partial unique
 *  index (and this repository's own active-lookup) treats as "in flight". */
const ACTIVE_STATES: readonly RefundIntentState[] = [
  'drafted',
  'approval_authored',
  'refund_event_appended',
];

export interface RefundIntentRow {
  id: string;
  terminal_id: string;
  operator_id: string;
  original_local_receipt_id: string;
  original_fiscal_event_id: string;
  line_snapshot_json: string;
  line_snapshot_fingerprint: string;
  approval_source_event_id: string;
  override_source_event_id: string;
  refund_fiscal_event_id: string | null;
  state: RefundIntentState;
  payout_confirmed_at: string | null;
  payout_disputed_at: string | null;
  printed_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CreateRefundIntentInput {
  /** The intent's own stable UUID -- becomes the refund's fiscal-event
   *  `source_event_id` (§4.3), so it MUST be generated by the caller
   *  before any approval authoring, never inside this repository. */
  id: string;
  terminalId: string;
  operatorId: string;
  originalLocalReceiptId: string;
  originalFiscalEventId: string;
  /** The frozen `original_line_references[]`/`line_items[]` pair (§3.1)
   *  this specific refund attempt covers -- any JSON-serializable value. */
  lineSnapshot: unknown;
  /** Pre-generated at row creation (§4.2), before the manager PIN is
   *  even entered -- durable, known in advance, unaffected by restart. */
  approvalSourceEventId: string;
  overrideSourceEventId: string;
}

export class InvalidRefundIntentTransitionError extends Error {
  constructor(
    public readonly id: string,
    public readonly toState: RefundIntentState,
    public readonly expectedFromStates: readonly RefundIntentState[],
  ) {
    super(
      `refund_intents ${id}: cannot transition to '${toState}' -- row does not exist or is not currently in one of [${expectedFromStates.join(', ')}].`,
    );
    this.name = 'InvalidRefundIntentTransitionError';
  }
}

/**
 * Stable fingerprint of a frozen line snapshot -- the active-intent
 * uniqueness key's second column (spec §4.4). Canonical `JSON.stringify`
 * ordering is sufficient here (unlike the signed fiscal payload, this
 * fingerprint is never hashed into the chain or compared cross-language
 * -- it is a purely LOCAL, device-own deduplication key).
 */
export async function computeLineSnapshotFingerprint(lineSnapshot: unknown): Promise<string> {
  return sha256(JSON.stringify(lineSnapshot));
}

export async function getRefundIntentById(
  db: Database,
  id: string,
): Promise<RefundIntentRow | null> {
  return queryOne<RefundIntentRow>(db, 'SELECT * FROM refund_intents WHERE id = $1', [id]);
}

/**
 * Looked up by the SAME key the partial unique index scopes (spec §4.4):
 * a cashier retry, double-click, or reopened cart for the SAME
 * original+line selection must find and reuse this row rather than
 * attempting a second `INSERT` (which the index would reject anyway --
 * this lookup lets the caller short-circuit with a clean read instead of
 * relying on catching a constraint-violation exception).
 */
export async function findActiveRefundIntent(
  db: Database,
  originalLocalReceiptId: string,
  lineSnapshotFingerprint: string,
): Promise<RefundIntentRow | null> {
  const placeholders = ACTIVE_STATES.map((_, i) => `$${String(i + 3)}`).join(', ');
  return queryOne<RefundIntentRow>(
    db,
    `SELECT * FROM refund_intents
      WHERE original_local_receipt_id = $1
        AND line_snapshot_fingerprint = $2
        AND state IN (${placeholders})
      ORDER BY created_at DESC
      LIMIT 1`,
    [originalLocalReceiptId, lineSnapshotFingerprint, ...ACTIVE_STATES],
  );
}

/**
 * The primary entry point for beginning a refund: computes the
 * fingerprint, looks up an existing ACTIVE row for the same
 * original+line selection, and reuses it if found -- otherwise inserts a
 * fresh `'drafted'` row. This is the idempotent semantics the active-
 * intent partial unique index exists to enforce; callers should not
 * `INSERT` directly.
 */
export async function createOrReuseActiveRefundIntent(
  db: Database,
  input: CreateRefundIntentInput,
): Promise<{ intent: RefundIntentRow; reused: boolean }> {
  const fingerprint = await computeLineSnapshotFingerprint(input.lineSnapshot);
  const existing = await findActiveRefundIntent(db, input.originalLocalReceiptId, fingerprint);
  if (existing !== null) {
    return { intent: existing, reused: true };
  }

  await execute(
    db,
    `INSERT INTO refund_intents (
       id, terminal_id, operator_id, original_local_receipt_id, original_fiscal_event_id,
       line_snapshot_json, line_snapshot_fingerprint, approval_source_event_id,
       override_source_event_id, state, created_at, updated_at
     ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'drafted', datetime('now'), datetime('now'))`,
    [
      input.id,
      input.terminalId,
      input.operatorId,
      input.originalLocalReceiptId,
      input.originalFiscalEventId,
      JSON.stringify(input.lineSnapshot),
      fingerprint,
      input.approvalSourceEventId,
      input.overrideSourceEventId,
    ],
  );

  const created = await getRefundIntentById(db, input.id);
  if (created === null) {
    throw new Error(`refund_intents ${input.id}: INSERT reported success but the row cannot be read back.`);
  }
  return { intent: created, reused: false };
}

/**
 * The single state-transition primitive every named transition below
 * delegates to -- guards `WHERE id = $1 AND state IN (fromStates)` so an
 * invalid transition (row missing, or already past the expected state)
 * updates ZERO rows rather than silently overwriting a state a
 * concurrent/earlier step already advanced past.
 */
async function transitionRefundIntentState(
  db: Database,
  id: string,
  fromStates: readonly RefundIntentState[],
  toState: RefundIntentState,
  extraSetClause?: string,
  extraParams?: unknown[],
): Promise<void> {
  const fromPlaceholderStart = 3 + (extraParams?.length ?? 0);
  const fromPlaceholders = fromStates
    .map((_, i) => `$${String(fromPlaceholderStart + i)}`)
    .join(', ');
  const result = await execute(
    db,
    `UPDATE refund_intents
        SET state = $2, updated_at = datetime('now')${extraSetClause ? `, ${extraSetClause}` : ''}
      WHERE id = $1
        AND state IN (${fromPlaceholders})`,
    [id, toState, ...(extraParams ?? []), ...fromStates],
  );
  if (result.rowsAffected === 0) {
    throw new InvalidRefundIntentTransitionError(id, toState, fromStates);
  }
}

export async function markApprovalAuthored(db: Database, id: string): Promise<void> {
  await transitionRefundIntentState(db, id, ['drafted'], 'approval_authored');
}

/**
 * §4.3 — `refund_fiscal_event_id` is only known AFTER `engine.append()`
 * returns; this is the "read-back convenience" write, never the
 * idempotency mechanism (that is `engine.append()`'s own
 * `source_event_class`/`source_event_id` dedup, keyed on this intent's
 * own `id`).
 */
export async function markRefundEventAppended(
  db: Database,
  id: string,
  refundFiscalEventId: string,
): Promise<void> {
  await transitionRefundIntentState(
    db,
    id,
    ['approval_authored'],
    'refund_event_appended',
    'refund_fiscal_event_id = $3',
    [refundFiscalEventId],
  );
}

/** §4.6 — terminal for local purposes; the device never claims knowledge
 *  of server-side projection success/failure beyond this. */
export async function markSynced(db: Database, id: string): Promise<void> {
  await transitionRefundIntentState(db, id, ['refund_event_appended'], 'synced');
}

/** The append itself permanently failed -- no fiscal event exists.
 *  Reachable from 'drafted' or 'approval_authored' only; once a fiscal
 *  event has been appended (`refund_event_appended`), this row can never
 *  legitimately claim "no event exists". */
export async function markDeadLetteredLocal(db: Database, id: string): Promise<void> {
  await transitionRefundIntentState(db, id, ['drafted', 'approval_authored'], 'dead_lettered_local');
}

/** Cashier abandons the refund before it is ever signed. */
export async function markAbandoned(db: Database, id: string): Promise<void> {
  await transitionRefundIntentState(db, id, ['drafted', 'approval_authored'], 'abandoned');
}

/**
 * §4.5 — set only by an explicit cashier action AFTER
 * `refund_event_appended`; the fiscal event's already-signed effect is
 * never touched, this is purely local bookkeeping.
 */
export async function confirmRefundIntentPayout(db: Database, id: string): Promise<void> {
  await execute(
    db,
    `UPDATE refund_intents
        SET payout_confirmed_at = datetime('now'), updated_at = datetime('now')
      WHERE id = $1 AND refund_fiscal_event_id IS NOT NULL`,
    [id],
  );
}

/**
 * §4.5 Revision 4 fold -- the "No / Not sure" branch. Does NOT change the
 * fiscal event's already-signed effect and does NOT exclude the refund
 * from the device Z's expected-cash subtraction (that lives entirely on
 * the `offline_receipts` row, a separate table) -- purely a server-side
 * evidence signal surfaced for finance-team investigation.
 */
export async function disputeRefundIntentPayout(db: Database, id: string): Promise<void> {
  await execute(
    db,
    `UPDATE refund_intents
        SET payout_disputed_at = datetime('now'), updated_at = datetime('now')
      WHERE id = $1 AND refund_fiscal_event_id IS NOT NULL`,
    [id],
  );
}

export async function confirmRefundIntentPrinted(db: Database, id: string): Promise<void> {
  await execute(
    db,
    `UPDATE refund_intents SET printed_at = datetime('now'), updated_at = datetime('now') WHERE id = $1`,
    [id],
  );
}

/**
 * §4.5 — app-start reconciliation screen trigger: a refund fiscal event
 * exists but the cashier never confirmed the cash handover (crash-
 * around-handover window).
 */
export async function getRefundIntentsPendingPayoutConfirmation(
  db: Database,
): Promise<RefundIntentRow[]> {
  return queryAll<RefundIntentRow>(
    db,
    `SELECT * FROM refund_intents
      WHERE refund_fiscal_event_id IS NOT NULL AND payout_confirmed_at IS NULL
      ORDER BY created_at ASC`,
  );
}

/**
 * §4.5 print-recovery -- payout confirmed but the AVOIR was never
 * printed (app start prompt: "print it now?").
 */
export async function getRefundIntentsPendingReprint(db: Database): Promise<RefundIntentRow[]> {
  return queryAll<RefundIntentRow>(
    db,
    `SELECT * FROM refund_intents
      WHERE payout_confirmed_at IS NOT NULL AND printed_at IS NULL
      ORDER BY payout_confirmed_at ASC`,
  );
}

/**
 * v3-refund-chain-integration wave-2 review fix, ORCHESTRATOR-RULED
 * (promoted from treasury's recommendation to REQUIRED) — device-local
 * cumulative-quantity BACKSTOP. §12's server-side per-original quantity-
 * cap lock (`FOR UPDATE` + `ABS()`-normalized query,
 * `PosCoreReceiptProjection.php`) remains the sole CROSS-TERMINAL
 * authority; this is a single-device, best-effort BELT that closes a
 * full-refund-value cash-loss class for tenant #1's whole (single-
 * terminal) topology at trivial local-query cost, well before any network
 * round trip: a device that has ALREADY appended two refund fiscal events
 * covering the original's full quantity must refuse a third attempt
 * locally, rather than authoring a doomed-to-be-rejected fiscal event (or
 * worse, succeeding locally while the server-side lock is the only thing
 * standing between the tenant and a double payout).
 *
 * Sums the ALREADY-refunded quantity per `original_line_index`, decoded
 * from `line_snapshot_json`, across every `refund_intents` row for the
 * SAME `original_local_receipt_id` that has reached a state PROVING a
 * fiscal event was actually appended (`refund_event_appended` or
 * `synced`) — `drafted`/`approval_authored`/`dead_lettered_local`/
 * `abandoned` never signed anything real and must never count toward the
 * cap (an abandoned draft is not a refunded unit).
 *
 * **⚖️ Q-1 ruling, wave-2 fix wave (finding 18) — this function FAILS
 * CLOSED.** It previously SKIPPED a row with malformed JSON, a non-array
 * snapshot, or an entry missing the expected shape, on the reasoning that
 * "count what it can parse" beats a parse error blocking every subsequent
 * refund. That reasoning is backwards for a cap: skipping an
 * already-appended refund UNDERCOUNTS what has been refunded, which makes
 * the backstop *more permissive* precisely when its data is untrustworthy
 * — the direction that loses money. An unreadable prior snapshot now
 * throws {@link CumulativeRefundSnapshotUnreadableError} and the caller
 * refuses the refund. (The device is not left stranded: §12's server-side
 * cap remains the sole cross-terminal authority and the back office can
 * still process the return.)
 *
 * **Quantity is a decimal STRING (finding 18's sibling, finding 3 /
 * codex C-2).** The snapshot entry's `quantity` is the canonical positive
 * decimal string normalized ONCE at the refund boundary
 * (`buildV4RefundLines()`); it is summed verbatim. The old code read a
 * number off `cartItem.quantity` and re-derived a string with
 * `Math.abs(q).toFixed(4)` — a second, divergent derivation of a value
 * the payload builder formatted differently, contaminating the cap and
 * breaking the §3.3 parallel-array byte-equality invariant.
 */
export class CumulativeRefundSnapshotUnreadableError extends Error {
  readonly i18nKey = 'refundFlow.refundQuantityExceeded';

  constructor(
    public readonly originalLocalReceiptId: string,
    public readonly detail: string,
  ) {
    super(
      `refund_intents cumulative-quantity backstop: an ALREADY-APPENDED refund snapshot for original ${originalLocalReceiptId} is unreadable (${detail}). Refusing the refund rather than undercounting the already-refunded quantity (⚖️ Q-1 ruling, spec §4.4 erratum).`,
    );
    this.name = 'CumulativeRefundSnapshotUnreadableError';
  }
}

/** Canonical positive decimal quantity string, `QUANTITY_SCALE` places. */
const QUANTITY_STRING_PATTERN = /^\d+(\.\d+)?$/;

export async function getCumulativeRefundedQuantityByOriginalLine(
  db: Database,
  originalLocalReceiptId: string,
): Promise<Map<number, string>> {
  const rows = await queryAll<{ line_snapshot_json: string }>(
    db,
    `SELECT line_snapshot_json FROM refund_intents
      WHERE original_local_receipt_id = $1
        AND state IN ('refund_event_appended', 'synced')`,
    [originalLocalReceiptId],
  );

  const refuse = (detail: string): never => {
    throw new CumulativeRefundSnapshotUnreadableError(originalLocalReceiptId, detail);
  };

  const totals = new Map<number, string>();
  for (const row of rows) {
    let entries: unknown;
    try {
      entries = JSON.parse(row.line_snapshot_json);
    } catch {
      refuse('line_snapshot_json is not parseable JSON');
    }
    if (!Array.isArray(entries)) {
      refuse('line_snapshot_json is not an array');
    }

    for (const entry of entries as unknown[]) {
      if (typeof entry !== 'object' || entry === null || Array.isArray(entry)) {
        refuse('a snapshot entry is not an object');
      }
      const record = entry as Record<string, unknown>;

      const originalLineIndex = record['originalLineIndex'];
      if (typeof originalLineIndex !== 'number' || !Number.isInteger(originalLineIndex)) {
        refuse('a snapshot entry has no integer originalLineIndex');
      }

      // Canonical decimal string only — a number here means the snapshot
      // predates finding 3's fix or was written by something that is not
      // `buildV4RefundLines()`. Either way it cannot be trusted to sum
      // exactly, so it is refused rather than coerced.
      const quantity = record['quantity'];
      if (typeof quantity !== 'string' || !QUANTITY_STRING_PATTERN.test(quantity)) {
        refuse('a snapshot entry has no canonical positive decimal quantity string');
      }

      const existing = totals.get(originalLineIndex as number) ?? '0';
      totals.set(
        originalLineIndex as number,
        bcadd(existing, quantity as string, QUANTITY_SCALE),
      );
    }
  }
  return totals;
}
